In [1]:
import pandas as pd
import numpy as np

In [49]:
data = pd.read_csv("training-ds.csv")

In [50]:
data

,Tipo de Red,Estudiante de Tecnología,Nivel de Educación,Vive en Ciudad,Tipo de Instituto,Edad,Dispositivo,Tipo de Internet,Situación Financiera,Género,Duración de la Clase,Nivel de Adaptación
0,3G,Si,Universidad,Si,Privado,21-25,Computadora,Wifi,Media,Masculino,03-Jun,Bajo
1,3G,No,Escuela,Si,Privado,Nov-15,Smartphone,Compra Megas,Media,Femenino,01-Mar,Moderado
2,3G,Si,Universidad,Si,Privado,21-25,Smartphone,Compra Megas,Mala,Masculino,01-Mar,Bajo
3,3G,Si,Escuela,Si,Privado,Nov-15,Smartphone,Compra Megas,Media,Masculino,01-Mar,Moderado
4,4G,Si,Universidad,Si,Privado,21-25,Computadora,Wifi,Buena,Masculino,01-Mar,Alto
...,...,...,...,...,...,...,...,...,...,...,...,...
959,3G,No,Universidad,Si,Privado,21-25,Smartphone,Compra Megas,Media,Masculino,01-Mar,Moderado
960,3G,No,Escuela,Si,Privado,Nov-15,Smartphone,Compra Megas,Media,Femenino,01-Mar,Moderado
961,4G,No,Universidad,Si,Público,21-25,Smartphone,Compra Megas,Media,Masculino,0,Bajo
962,3G,No,Universidad,Si,Privado,21-25,Smartphone,Compra Megas,Media,Masculino,01-Mar,Moderado
963,4G,No,Escuela,Si,Privado,01-May,Smartphone,Compra Megas,Media,Femenino,01-Mar,Moderado

In [51]:
def convertir_mes_a_numero(fecha):
    if len(fecha) == 5 and fecha[1] == '-' and fecha[2:].isdigit():
        return fecha  
    
    meses = {
        'Jan': '1', 'Feb': '2', 'Mar': '3', 'Apr': '4',
        'May': '5', 'Jun': '6', 'Jul': '7', 'Aug': '8',
        'Sep': '9', 'Oct': '10', 'Nov': '11', 'Dec': '12'
    }
    if len(fecha) == 6 and fecha[2] == '-' and fecha[:2].isdigit():
        numero_mes = meses.get(fecha[3:])
        if numero_mes:
            return f"{int(fecha[:2])}-{numero_mes.zfill(2)}"
    
    partes = fecha.split('-')
    numero_mes = meses.get(partes[0])
    if numero_mes:
        return f"{numero_mes}-{partes[1]}"
    else:
        return fecha 

data['Edad'] = data['Edad'].apply(convertir_mes_a_numero)

In [52]:
data

,Tipo de Red,Estudiante de Tecnología,Nivel de Educación,Vive en Ciudad,Tipo de Instituto,Edad,Dispositivo,Tipo de Internet,Situación Financiera,Género,Duración de la Clase,Nivel de Adaptación
0,3G,Si,Universidad,Si,Privado,21-25,Computadora,Wifi,Media,Masculino,03-Jun,Bajo
1,3G,No,Escuela,Si,Privado,11-15,Smartphone,Compra Megas,Media,Femenino,01-Mar,Moderado
2,3G,Si,Universidad,Si,Privado,21-25,Smartphone,Compra Megas,Mala,Masculino,01-Mar,Bajo
3,3G,Si,Escuela,Si,Privado,11-15,Smartphone,Compra Megas,Media,Masculino,01-Mar,Moderado
4,4G,Si,Universidad,Si,Privado,21-25,Computadora,Wifi,Buena,Masculino,01-Mar,Alto
...,...,...,...,...,...,...,...,...,...,...,...,...
959,3G,No,Universidad,Si,Privado,21-25,Smartphone,Compra Megas,Media,Masculino,01-Mar,Moderado
960,3G,No,Escuela,Si,Privado,11-15,Smartphone,Compra Megas,Media,Femenino,01-Mar,Moderado
961,4G,No,Universidad,Si,Público,21-25,Smartphone,Compra Megas,Media,Masculino,0,Bajo
962,3G,No,Universidad,Si,Privado,21-25,Smartphone,Compra Megas,Media,Masculino,01-Mar,Moderado
963,4G,No,Escuela,Si,Privado,1-05,Smartphone,Compra Megas,Media,Femenino,01-Mar,Moderado

In [53]:
display(data.dtypes)

Tipo de Red                 object
Estudiante de Tecnología    object
Nivel de Educación          object
Vive en Ciudad              object
Tipo de Instituto           object
Edad                        object
Dispositivo                 object
Tipo de Internet            object
Situación Financiera        object
Género                      object
Duración de la Clase        object
Nivel de Adaptación         object
dtype: object

In [54]:
def print_unique_values(data_frame, dtype='object'):
    for column in data_frame.columns:
        if data_frame[column].dtype == dtype:
            print(f'{column}: {list(data_frame[column].unique())}')


print_unique_values(data)

Tipo de Red: ['3G', '4G', '2G']
Estudiante de Tecnología: ['Si', 'No']
Nivel de Educación: ['Universidad', 'Escuela', 'Colegio']
Vive en Ciudad: ['Si', 'No']
Tipo de Instituto: ['Privado', 'Público']
Edad: ['21-25', '11-15', '16-20', '26-30', '1-05', '6-10']
Dispositivo: ['Computadora', 'Smartphone', 'Tableta']
Tipo de Internet: ['Wifi', 'Compra Megas']
Situación Financiera: ['Media', 'Mala', 'Buena']
Género: ['Masculino', 'Femenino']
Duración de la Clase: ['03-Jun', '01-Mar', '0']
Nivel de Adaptación: ['Bajo', 'Moderado', 'Alto']

In [55]:
data_transform= data
data_transform = pd.get_dummies(data, columns=[ 'Estudiante de Tecnología', "Vive en Ciudad",'Tipo de Instituto','Tipo de Internet','Género'])
display(data_transform.head(100))

,Tipo de Red,Nivel de Educación,Edad,Dispositivo,Situación Financiera,Duración de la Clase,Nivel de Adaptación,Estudiante de Tecnología_No,Estudiante de Tecnología_Si,Vive en Ciudad_No,Vive en Ciudad_Si,Tipo de Instituto_Privado,Tipo de Instituto_Público,Tipo de Internet_Compra Megas,Tipo de Internet_Wifi,Género_Femenino,Género_Masculino
0,3G,Universidad,21-25,Computadora,Media,03-Jun,Bajo,0,1,0,1,1,0,0,1,0,1
1,3G,Escuela,11-15,Smartphone,Media,01-Mar,Moderado,1,0,0,1,1,0,1,0,1,0
2,3G,Universidad,21-25,Smartphone,Mala,01-Mar,Bajo,0,1,0,1,1,0,1,0,0,1
3,3G,Escuela,11-15,Smartphone,Media,01-Mar,Moderado,0,1,0,1,1,0,1,0,0,1
4,4G,Universidad,21-25,Computadora,Buena,01-Mar,Alto,0,1,0,1,1,0,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,4G,Colegio,16-20,Smartphone,Media,0,Bajo,0,1,1,0,0,1,1,0,0,1
96,4G,Escuela,16-20,Computadora,Media,01-Mar,Bajo,1,0,0,1,1,0,0,1,1,0
97,4G,Universidad,21-25,Smartphone,Media,0,Bajo,1,0,0,1,1,0,1,0,0,1
98,3G,Universidad,21-25,Smartphone,Media,01-Mar,Bajo,1,0,0,1,0,1,1,0,0,1
99,3G,Escuela,6-10,Smartphone,Media,01-Mar,Bajo,1,0,0,1,1,0,1,0,0,1

In [56]:
def print_zeros_values(data_frame):
    for column in data_frame.columns:
        print (f'{column}: {sum(data_frame[column] == 0)}')

print_zeros_values(data_transform)

Tipo de Red: 0
Nivel de Educación: 0
Edad: 0
Dispositivo: 0
Situación Financiera: 0
Duración de la Clase: 0
Nivel de Adaptación: 0
Estudiante de Tecnología_No: 243
Estudiante de Tecnología_Si: 721
Vive en Ciudad_No: 756
Vive en Ciudad_Si: 208
Tipo de Instituto_Privado: 302
Tipo de Instituto_Público: 662
Tipo de Internet_Compra Megas: 413
Tipo de Internet_Wifi: 551
Género_Femenino: 532
Género_Masculino: 432

In [57]:
print(data_transform.columns)
print(data.columns)

Index(['Tipo de Red', 'Nivel de Educación', 'Edad', 'Dispositivo',
       'Situación Financiera', 'Duración de la Clase', 'Nivel de Adaptación',
       'Estudiante de Tecnología_No', 'Estudiante de Tecnología_Si',
       'Vive en Ciudad_No', 'Vive en Ciudad_Si', 'Tipo de Instituto_Privado',
       'Tipo de Instituto_Público', 'Tipo de Internet_Compra Megas',
       'Tipo de Internet_Wifi', 'Género_Femenino', 'Género_Masculino'],
      dtype='object')
Index(['Tipo de Red', 'Estudiante de Tecnología', 'Nivel de Educación',
       'Vive en Ciudad', 'Tipo de Instituto', 'Edad', 'Dispositivo',
       'Tipo de Internet', 'Situación Financiera', 'Género',
       'Duración de la Clase', 'Nivel de Adaptación'],
      dtype='object')

In [58]:
data_transform = data_transform.rename(columns={'Nivel de Adaptación':'Nivel de Adaptacion'})
data_transform.insert(loc=len(data_transform.columns)-1, column='Nivel de Adaptacion', value=data_transform.pop('Nivel de Adaptacion'))

In [59]:
data_transform.columns
type(data_transform['Nivel de Adaptacion'])

pandas.core.series.Series

In [60]:
correlation_level_adaption = data_transform.corrwith(data_transform['Nivel de Adaptacion'], method='kendall')
# Ordenar por valor absoluto en orden descendente
correlation_level_adaption = correlation_level_adaption.abs().sort_values(ascending=False)
print(correlation_level_adaption.head(11))

Tipo de Instituto_Privado        0.205034
Tipo de Instituto_Público        0.205034
Vive en Ciudad_No                0.136796
Vive en Ciudad_Si                0.136796
Estudiante de Tecnología_No      0.064079
Estudiante de Tecnología_Si      0.064079
Tipo de Internet_Compra Megas    0.049212
Tipo de Internet_Wifi            0.049212
Género_Femenino                  0.024113
Género_Masculino                 0.024113
dtype: float64

C:\Users\miky1\AppData\Local\Temp\ipykernel_11068\2588461948.py:1: FutureWarning: The default value of numeric_only in DataFrame.corrwith is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  correlation_level_adaption = data_transform.corrwith(data_transform['Nivel de Adaptacion'], method='kendall')

In [64]:
correlation_level_adaption = data.corrwith(data['Nivel de Adaptación'], method='kendall')
# Ordenar por valor absoluto en orden descendente
correlation_level_adaption[0]

C:\Users\miky1\AppData\Local\Temp\ipykernel_11068\4178111065.py:1: FutureWarning: The default value of numeric_only in DataFrame.corrwith is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  correlation_level_adaption = data.corrwith(data['Nivel de Adaptación'], method='kendall')

IndexError: index 0 is out of bounds for axis 0 with size 0

In [62]:
data

,Tipo de Red,Estudiante de Tecnología,Nivel de Educación,Vive en Ciudad,Tipo de Instituto,Edad,Dispositivo,Tipo de Internet,Situación Financiera,Género,Duración de la Clase,Nivel de Adaptación
0,3G,Si,Universidad,Si,Privado,21-25,Computadora,Wifi,Media,Masculino,03-Jun,Bajo
1,3G,No,Escuela,Si,Privado,11-15,Smartphone,Compra Megas,Media,Femenino,01-Mar,Moderado
2,3G,Si,Universidad,Si,Privado,21-25,Smartphone,Compra Megas,Mala,Masculino,01-Mar,Bajo
3,3G,Si,Escuela,Si,Privado,11-15,Smartphone,Compra Megas,Media,Masculino,01-Mar,Moderado
4,4G,Si,Universidad,Si,Privado,21-25,Computadora,Wifi,Buena,Masculino,01-Mar,Alto
...,...,...,...,...,...,...,...,...,...,...,...,...
959,3G,No,Universidad,Si,Privado,21-25,Smartphone,Compra Megas,Media,Masculino,01-Mar,Moderado
960,3G,No,Escuela,Si,Privado,11-15,Smartphone,Compra Megas,Media,Femenino,01-Mar,Moderado
961,4G,No,Universidad,Si,Público,21-25,Smartphone,Compra Megas,Media,Masculino,0,Bajo
962,3G,No,Universidad,Si,Privado,21-25,Smartphone,Compra Megas,Media,Masculino,01-Mar,Moderado
963,4G,No,Escuela,Si,Privado,1-05,Smartphone,Compra Megas,Media,Femenino,01-Mar,Moderado

In [70]:
from scipy.stats import chi2_contingency
df = pd.DataFrame(data)

# Obtener todas las columnas categóricas (excluyendo la columna 'Nivel de Adaptación')
categorical_columns = df.select_dtypes(include=['object']).columns.tolist()
categorical_columns.remove('Nivel de Adaptación')

# Realizar la prueba de Chi-cuadrado para cada columna categórica
results = {}
for column in categorical_columns:
    contingency_table = pd.crosstab(df['Nivel de Adaptación'], df[column])
    chi2, p, _, _ = chi2_contingency(contingency_table)
    results[column] = {'Chi-cuadrado': chi2, 'Valor p': p}

# Mostrar los resultados
for column, result in results.items():
    print(f"Variable: {column}")
    print(f"Chi-cuadrado: {result['Chi-cuadrado']}")
    print(f"Valor p: {result['Valor p']}")
    print("---------")

Variable: Tipo de Red
Chi-cuadrado: 22.416899468049962
Valor p: 0.00016553607337707634
---------
Variable: Estudiante de Tecnología
Chi-cuadrado: 18.071856218207742
Valor p: 0.00011905462826913621
---------
Variable: Nivel de Educación
Chi-cuadrado: 34.12387833220294
Valor p: 7.028430339688034e-07
---------
Variable: Vive en Ciudad
Chi-cuadrado: 58.93948394141377
Valor p: 1.590207066435886e-13
---------
Variable: Tipo de Instituto
Chi-cuadrado: 86.2495346195265
Valor p: 1.8670309785740592e-19
---------
Variable: Edad
Chi-cuadrado: 99.38765927838557
Valor p: 7.225920028459192e-17
---------
Variable: Dispositivo
Chi-cuadrado: 43.667029513202095
Valor p: 7.523116516226196e-09
---------
Variable: Tipo de Internet
Chi-cuadrado: 14.865597060186293
Valor p: 0.000591529779493374
---------
Variable: Situación Financiera
Chi-cuadrado: 169.29098707058372
Valor p: 1.4846830691108703e-35
---------
Variable: Género
Chi-cuadrado: 11.77281525381296
Valor p: 0.0027769345850669797
---------
Variable: Duración de la Clase
Chi-cuadrado: 175.07187246811478
Valor p: 8.526003556326326e-37
---------

In [71]:
significative_columns = [column for column, result in results.items() if result['Valor p'] < 0.05]

# Utilizar estas columnas significativas para entrenar tu red neuronal
# X serían tus datos con estas columnas seleccionadas y 'Nivel de Adaptación' sería tu variable objetivo
X = df[significative_columns]
y = df['Nivel de Adaptación']

In [74]:
significative_columns

['Tipo de Red',
 'Estudiante de Tecnología',
 'Nivel de Educación',
 'Vive en Ciudad',
 'Tipo de Instituto',
 'Edad',
 'Dispositivo',
 'Tipo de Internet',
 'Situación Financiera',
 'Género',
 'Duración de la Clase']