In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
from scipy.stats import chi2_contingency

In [2]:
data = pd.read_csv("training-ds.csv")
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 964 entries, 0 to 963
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Tipo de Red               964 non-null    object
 1   Estudiante de Tecnología  964 non-null    object
 2   Nivel de Educación        964 non-null    object
 3   Vive en Ciudad            964 non-null    object
 4   Tipo de Instituto         964 non-null    object
 5   Edad                      964 non-null    object
 6   Dispositivo               964 non-null    object
 7   Tipo de Internet          964 non-null    object
 8   Situación Financiera      964 non-null    object
 9   Género                    964 non-null    object
 10  Duración de la Clase      964 non-null    object
 11  Nivel de Adaptación       964 non-null    object
dtypes: object(12)
memory usage: 90.5+ KB
None

In [3]:
data.shape

(964, 12)

In [4]:
def convertir_mes_a_numero(fecha):
    if len(fecha) == 5 and fecha[1] == '-' and fecha[2:].isdigit():
        return fecha  
    
    meses = {
        'Jan': '1', 'Feb': '2', 'Mar': '3', 'Apr': '4',
        'May': '5', 'Jun': '6', 'Jul': '7', 'Aug': '8',
        'Sep': '9', 'Oct': '10', 'Nov': '11', 'Dec': '12'
    }
    if len(fecha) == 6 and fecha[2] == '-' and fecha[:2].isdigit():
        numero_mes = meses.get(fecha[3:])
        if numero_mes:
            return f"{int(fecha[:2])}-{numero_mes.zfill(2)}"
    
    partes = fecha.split('-')
    numero_mes = meses.get(partes[0])
    if numero_mes:
        return f"{numero_mes}-{partes[1]}"
    else:
        return fecha 

data['Edad'] = data['Edad'].apply(convertir_mes_a_numero)
data['Duración de la Clase'] = data['Duración de la Clase'].apply(convertir_mes_a_numero)

In [5]:
data

,Tipo de Red,Estudiante de Tecnología,Nivel de Educación,Vive en Ciudad,Tipo de Instituto,Edad,Dispositivo,Tipo de Internet,Situación Financiera,Género,Duración de la Clase,Nivel de Adaptación
0,3G,Si,Universidad,Si,Privado,21-25,Computadora,Wifi,Media,Masculino,3-06,Bajo
1,3G,No,Escuela,Si,Privado,11-15,Smartphone,Compra Megas,Media,Femenino,1-03,Moderado
2,3G,Si,Universidad,Si,Privado,21-25,Smartphone,Compra Megas,Mala,Masculino,1-03,Bajo
3,3G,Si,Escuela,Si,Privado,11-15,Smartphone,Compra Megas,Media,Masculino,1-03,Moderado
4,4G,Si,Universidad,Si,Privado,21-25,Computadora,Wifi,Buena,Masculino,1-03,Alto
...,...,...,...,...,...,...,...,...,...,...,...,...
959,3G,No,Universidad,Si,Privado,21-25,Smartphone,Compra Megas,Media,Masculino,1-03,Moderado
960,3G,No,Escuela,Si,Privado,11-15,Smartphone,Compra Megas,Media,Femenino,1-03,Moderado
961,4G,No,Universidad,Si,Público,21-25,Smartphone,Compra Megas,Media,Masculino,0,Bajo
962,3G,No,Universidad,Si,Privado,21-25,Smartphone,Compra Megas,Media,Masculino,1-03,Moderado
963,4G,No,Escuela,Si,Privado,1-05,Smartphone,Compra Megas,Media,Femenino,1-03,Moderado

In [6]:
display(data.dtypes)

Tipo de Red                 object
Estudiante de Tecnología    object
Nivel de Educación          object
Vive en Ciudad              object
Tipo de Instituto           object
Edad                        object
Dispositivo                 object
Tipo de Internet            object
Situación Financiera        object
Género                      object
Duración de la Clase        object
Nivel de Adaptación         object
dtype: object

In [7]:
def print_unique_values(data_frame, dtype='object'):
    for column in data_frame.columns:
        if data_frame[column].dtype == dtype:
            print(f'{column}: {list(data_frame[column].unique())}')


print_unique_values(data)

Tipo de Red: ['3G', '4G', '2G']
Estudiante de Tecnología: ['Si', 'No']
Nivel de Educación: ['Universidad', 'Escuela', 'Colegio']
Vive en Ciudad: ['Si', 'No']
Tipo de Instituto: ['Privado', 'Público']
Edad: ['21-25', '11-15', '16-20', '26-30', '1-05', '6-10']
Dispositivo: ['Computadora', 'Smartphone', 'Tableta']
Tipo de Internet: ['Wifi', 'Compra Megas']
Situación Financiera: ['Media', 'Mala', 'Buena']
Género: ['Masculino', 'Femenino']
Duración de la Clase: ['3-06', '1-03', '0']
Nivel de Adaptación: ['Bajo', 'Moderado', 'Alto']

In [8]:
data_transform= data
data_transform = pd.get_dummies(data, columns=[ 'Estudiante de Tecnología', "Vive en Ciudad",'Tipo de Instituto','Tipo de Internet','Género'])
#display(data_transform.head(100))

In [9]:
# Crear el DataFrame
df = pd.DataFrame(data)
# Codificar las variables categóricas a números usando LabelEncoder
df_encoded = df.apply(LabelEncoder().fit_transform)
# Dividir el DataFrame en variables predictoras (X) y la variable objetivo (y)
X = df_encoded.drop('Nivel de Adaptación', axis=1)
y = df_encoded['Nivel de Adaptación']
# Inicializar el clasificador RandomForestClassifier
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)
# Entrenar el modelo
rf_classifier.fit(X, y)
# Obtener la importancia de las características
feature_importances = rf_classifier.feature_importances_
# Crear un DataFrame con las importancias de las características
importance_df = pd.DataFrame({'Feature': X.columns, 'Importance': feature_importances})
importance_df = importance_df.sort_values(by='Importance', ascending=False)
# Mostrar las características más importantes
importance_df

                     Feature  Importance
10      Duración de la Clase    0.181185
8       Situación Financiera    0.132298
5                       Edad    0.130287
9                     Género    0.098232
4          Tipo de Instituto    0.075108
2         Nivel de Educación    0.073862
0                Tipo de Red    0.071743
3             Vive en Ciudad    0.069197
7           Tipo de Internet    0.064026
1   Estudiante de Tecnología    0.053043
6                Dispositivo    0.051019

In [10]:
correlation_nivel_adaptacion = df_encoded.corr(method='pearson')['Nivel de Adaptación']
# Correlación con método pearson en orden ascendente
display((correlation_nivel_adaptacion[np.argsort(correlation_nivel_adaptacion, axis=0)[::-1]]).head(11))

Nivel de Adaptación         1.000000
Situación Financiera        0.258934
Duración de la Clase        0.209937
Vive en Ciudad              0.104525
Dispositivo                 0.066690
Estudiante de Tecnología    0.044715
Tipo de Red                 0.021874
Nivel de Educación         -0.015269
Género                     -0.042976
Tipo de Internet           -0.069489
Tipo de Instituto          -0.172572
Name: Nivel de Adaptación, dtype: float64

In [11]:
def print_zeros_values(data_frame):
    for column in data_frame.columns:
        print (f'{column}: {sum(data_frame[column] == 0)}')

print_zeros_values(data_transform)

Tipo de Red: 0
Nivel de Educación: 0
Edad: 0
Dispositivo: 0
Situación Financiera: 0
Duración de la Clase: 0
Nivel de Adaptación: 0
Estudiante de Tecnología_No: 243
Estudiante de Tecnología_Si: 721
Vive en Ciudad_No: 756
Vive en Ciudad_Si: 208
Tipo de Instituto_Privado: 302
Tipo de Instituto_Público: 662
Tipo de Internet_Compra Megas: 413
Tipo de Internet_Wifi: 551
Género_Femenino: 532
Género_Masculino: 432

In [12]:
data_transform = data_transform.rename(columns={'Nivel de Adaptación':'Nivel de Adaptacion'})
data_transform.insert(loc=len(data_transform.columns)-1, column='Nivel de Adaptacion', value=data_transform.pop('Nivel de Adaptacion'))

In [13]:
correlation_level_adaption = data_transform.corrwith(data_transform['Nivel de Adaptacion'], method='kendall')
# Ordenar por valor absoluto en orden descendente
correlation_level_adaption = correlation_level_adaption.abs().sort_values(ascending=False)
print(correlation_level_adaption.head(11))

Tipo de Instituto_Privado        0.205034
Tipo de Instituto_Público        0.205034
Vive en Ciudad_No                0.136796
Vive en Ciudad_Si                0.136796
Estudiante de Tecnología_No      0.064079
Estudiante de Tecnología_Si      0.064079
Tipo de Internet_Compra Megas    0.049212
Tipo de Internet_Wifi            0.049212
Género_Femenino                  0.024113
Género_Masculino                 0.024113
dtype: float64

C:\Users\miky1\AppData\Local\Temp\ipykernel_23960\2588461948.py:1: FutureWarning: The default value of numeric_only in DataFrame.corrwith is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  correlation_level_adaption = data_transform.corrwith(data_transform['Nivel de Adaptacion'], method='kendall')

In [14]:
correlation_level_adaption = data.corrwith(data['Nivel de Adaptación'], method='kendall')
# Ordenar por valor absoluto en orden descendente
print(correlation_level_adaption)

Series([], dtype: float64)

C:\Users\miky1\AppData\Local\Temp\ipykernel_23960\1892343149.py:1: FutureWarning: The default value of numeric_only in DataFrame.corrwith is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  correlation_level_adaption = data.corrwith(data['Nivel de Adaptación'], method='kendall')

In [15]:

df_chi = pd.DataFrame(data)

# Obtener todas las columnas categóricas (excluyendo la columna 'Nivel de Adaptación')
categorical_columns = df_chi.select_dtypes(include=['object']).columns.tolist()
categorical_columns.remove('Nivel de Adaptación')

# Realizar la prueba de Chi-cuadrado para cada columna categórica
results = {}
for column in categorical_columns:
    contingency_table = pd.crosstab(df_chi['Nivel de Adaptación'], df_chi[column])
    chi2, p, _, _ = chi2_contingency(contingency_table)
    results[column] = {'Chi-cuadrado': chi2, 'Valor p': p}

# Mostrar los resultados
for column, result in results.items():
    print(f"Variable: {column}")
    print(f"Chi-cuadrado: {result['Chi-cuadrado']}")
    print(f"Valor p: {result['Valor p']}")
    print("---------")

Variable: Tipo de Red
Chi-cuadrado: 22.416899468049962
Valor p: 0.00016553607337707634
---------
Variable: Estudiante de Tecnología
Chi-cuadrado: 18.071856218207742
Valor p: 0.00011905462826913621
---------
Variable: Nivel de Educación
Chi-cuadrado: 34.12387833220294
Valor p: 7.028430339688034e-07
---------
Variable: Vive en Ciudad
Chi-cuadrado: 58.93948394141377
Valor p: 1.590207066435886e-13
---------
Variable: Tipo de Instituto
Chi-cuadrado: 86.2495346195265
Valor p: 1.8670309785740592e-19
---------
Variable: Edad
Chi-cuadrado: 99.38765927838557
Valor p: 7.225920028459192e-17
---------
Variable: Dispositivo
Chi-cuadrado: 43.667029513202095
Valor p: 7.523116516226196e-09
---------
Variable: Tipo de Internet
Chi-cuadrado: 14.865597060186293
Valor p: 0.000591529779493374
---------
Variable: Situación Financiera
Chi-cuadrado: 169.29098707058372
Valor p: 1.4846830691108703e-35
---------
Variable: Género
Chi-cuadrado: 11.77281525381296
Valor p: 0.0027769345850669797
---------
Variable: Duración de la Clase
Chi-cuadrado: 175.07187246811478
Valor p: 8.526003556326326e-37
---------

In [16]:
significative_columns = [column for column, result in results.items() if result['Valor p'] < 0.05]

# Utilizar estas columnas significativas para entrenar tu red neuronal
# X serían tus datos con estas columnas seleccionadas y 'Nivel de Adaptación' sería tu variable objetivo
X = df_chi[significative_columns]
y = df_chi['Nivel de Adaptación']

In [17]:
data2 = data
data2

,Tipo de Red,Estudiante de Tecnología,Nivel de Educación,Vive en Ciudad,Tipo de Instituto,Edad,Dispositivo,Tipo de Internet,Situación Financiera,Género,Duración de la Clase,Nivel de Adaptación
0,3G,Si,Universidad,Si,Privado,21-25,Computadora,Wifi,Media,Masculino,3-06,Bajo
1,3G,No,Escuela,Si,Privado,11-15,Smartphone,Compra Megas,Media,Femenino,1-03,Moderado
2,3G,Si,Universidad,Si,Privado,21-25,Smartphone,Compra Megas,Mala,Masculino,1-03,Bajo
3,3G,Si,Escuela,Si,Privado,11-15,Smartphone,Compra Megas,Media,Masculino,1-03,Moderado
4,4G,Si,Universidad,Si,Privado,21-25,Computadora,Wifi,Buena,Masculino,1-03,Alto
...,...,...,...,...,...,...,...,...,...,...,...,...
959,3G,No,Universidad,Si,Privado,21-25,Smartphone,Compra Megas,Media,Masculino,1-03,Moderado
960,3G,No,Escuela,Si,Privado,11-15,Smartphone,Compra Megas,Media,Femenino,1-03,Moderado
961,4G,No,Universidad,Si,Público,21-25,Smartphone,Compra Megas,Media,Masculino,0,Bajo
962,3G,No,Universidad,Si,Privado,21-25,Smartphone,Compra Megas,Media,Masculino,1-03,Moderado
963,4G,No,Escuela,Si,Privado,1-05,Smartphone,Compra Megas,Media,Femenino,1-03,Moderado

In [18]:
data['Nivel de Adaptación']

0          Bajo
1      Moderado
2          Bajo
3      Moderado
4          Alto
         ...
959    Moderado
960    Moderado
961        Bajo
962    Moderado
963    Moderado
Name: Nivel de Adaptación, Length: 964, dtype: object

In [19]:
#data = data2

In [20]:
# Mapear los valores de la columna 'Nivel de Adaptación' a números
mapping = {'Bajo': 0, 'Moderado': 1, 'Alto': 2}
data['Nivel de Adaptación'] = data['Nivel de Adaptación'].map(mapping)

# Verificar el resultado
print(data['Nivel de Adaptación'])

0      0
1      1
2      0
3      1
4      2
      ..
959    1
960    1
961    0
962    1
963    1
Name: Nivel de Adaptación, Length: 964, dtype: int64

In [21]:
data

,Tipo de Red,Estudiante de Tecnología,Nivel de Educación,Vive en Ciudad,Tipo de Instituto,Edad,Dispositivo,Tipo de Internet,Situación Financiera,Género,Duración de la Clase,Nivel de Adaptación
0,3G,Si,Universidad,Si,Privado,21-25,Computadora,Wifi,Media,Masculino,3-06,0
1,3G,No,Escuela,Si,Privado,11-15,Smartphone,Compra Megas,Media,Femenino,1-03,1
2,3G,Si,Universidad,Si,Privado,21-25,Smartphone,Compra Megas,Mala,Masculino,1-03,0
3,3G,Si,Escuela,Si,Privado,11-15,Smartphone,Compra Megas,Media,Masculino,1-03,1
4,4G,Si,Universidad,Si,Privado,21-25,Computadora,Wifi,Buena,Masculino,1-03,2
...,...,...,...,...,...,...,...,...,...,...,...,...
959,3G,No,Universidad,Si,Privado,21-25,Smartphone,Compra Megas,Media,Masculino,1-03,1
960,3G,No,Escuela,Si,Privado,11-15,Smartphone,Compra Megas,Media,Femenino,1-03,1
961,4G,No,Universidad,Si,Público,21-25,Smartphone,Compra Megas,Media,Masculino,0,0
962,3G,No,Universidad,Si,Privado,21-25,Smartphone,Compra Megas,Media,Masculino,1-03,1
963,4G,No,Escuela,Si,Privado,1-05,Smartphone,Compra Megas,Media,Femenino,1-03,1

In [22]:
x = data.drop('Nivel de Adaptación' , axis = 1)
y = data['Nivel de Adaptación']

In [23]:
y

0      0
1      1
2      0
3      1
4      2
      ..
959    1
960    1
961    0
962    1
963    1
Name: Nivel de Adaptación, Length: 964, dtype: int64

In [24]:

x_train , x_test , y_train , y_test = train_test_split(pd.get_dummies(x) , y , test_size = 0.2 , random_state = 42)

In [25]:
model = tf.keras.models.Sequential([
    tf.keras.layers.InputLayer(input_shape = x_train.shape[1:]),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.Dense(100 , activation = 'relu'),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.Dense(100 , activation = 'relu'),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.Dense(3 , activation = 'softmax')
])

model.compile(loss = tf.keras.losses.sparse_categorical_crossentropy , optimizer = tf.keras.optimizers.Adam() , metrics = ['accuracy'])

model.fit(x_train , y_train , epochs = 100)

Epoch 1/100

25/25 [==============================] - 1s 2ms/step - loss: 1.0116 - accuracy: 0.5694
Epoch 2/100
25/25 [==============================] - 0s 1ms/step - loss: 0.6700 - accuracy: 0.7315
Epoch 3/100
25/25 [==============================] - 0s 1ms/step - loss: 0.5713 - accuracy: 0.7847
Epoch 4/100
25/25 [==============================] - 0s 1ms/step - loss: 0.5211 - accuracy: 0.7886
Epoch 5/100
25/25 [==============================] - 0s 1ms/step - loss: 0.4489 - accuracy: 0.8223
Epoch 6/100
25/25 [==============================] - 0s 1ms/step - loss: 0.4402 - accuracy: 0.8197
Epoch 7/100
25/25 [==============================] - 0s 1ms/step - loss: 0.4175 - accuracy: 0.8405
Epoch 8/100
25/25 [==============================] - 0s 1ms/step - loss: 0.3988 - accuracy: 0.8327
Epoch 9/100
25/25 [==============================] - 0s 1ms/step - loss: 0.3691 - accuracy: 0.8560
Epoch 10/100
25/25 [==============================] - 0s 1ms/step - loss: 0.3622 - accuracy: 0.8495
Epoch 11/100
25/25 [==============================] - 0s 1ms/step - loss: 0.3513 - accuracy: 0.8768
Epoch 12/100
25/25 [==============================] - 0s 1ms/step - loss: 0.3515 - accuracy: 0.8612
Epoch 13/100
25/25 [==============================] - 0s 1ms/step - loss: 0.3600 - accuracy: 0.8612
Epoch 14/100
25/25 [==============================] - 0s 1ms/step - loss: 0.3581 - accuracy: 0.8560
Epoch 15/100
25/25 [==============================] - 0s 1ms/step - loss: 0.3391 - accuracy: 0.8729
Epoch 16/100
25/25 [==============================] - 0s 1ms/step - loss: 0.3548 - accuracy: 0.8612
Epoch 17/100
25/25 [==============================] - 0s 1ms/step - loss: 0.3523 - accuracy: 0.8547
Epoch 18/100
25/25 [==============================] - 0s 1ms/step - loss: 0.3283 - accuracy: 0.8638
Epoch 19/100
25/25 [==============================] - 0s 1ms/step - loss: 0.3333 - accuracy: 0.8638
Epoch 20/100
25/25 [==============================] - 0s 1ms/step - loss: 0.3173 - accuracy: 0.8716
Epoch 21/100
25/25 [==============================] - 0s 1ms/step - loss: 0.3296 - accuracy: 0.8599
Epoch 22/100
25/25 [==============================] - 0s 2ms/step - loss: 0.3311 - accuracy: 0.8651
Epoch 23/100
25/25 [==============================] - 0s 1ms/step - loss: 0.3145 - accuracy: 0.8677
Epoch 24/100
25/25 [==============================] - 0s 1ms/step - loss: 0.3115 - accuracy: 0.8742
Epoch 25/100
25/25 [==============================] - 0s 2ms/step - loss: 0.3251 - accuracy: 0.8599
Epoch 26/100
25/25 [==============================] - 0s 1ms/step - loss: 0.3144 - accuracy: 0.8729
Epoch 27/100
25/25 [==============================] - 0s 1ms/step - loss: 0.3256 - accuracy: 0.8742
Epoch 28/100
25/25 [==============================] - 0s 1ms/step - loss: 0.3178 - accuracy: 0.8690
Epoch 29/100
25/25 [==============================] - 0s 1ms/step - loss: 0.3058 - accuracy: 0.8651
Epoch 30/100
25/25 [==============================] - 0s 1ms/step - loss: 0.3045 - accuracy: 0.8703
Epoch 31/100
25/25 [==============================] - 0s 1ms/step - loss: 0.3181 - accuracy: 0.8625
Epoch 32/100
25/25 [==============================] - 0s 1ms/step - loss: 0.3188 - accuracy: 0.8651
Epoch 33/100
25/25 [==============================] - 0s 1ms/step - loss: 0.3252 - accuracy: 0.8638
Epoch 34/100
25/25 [==============================] - 0s 1ms/step - loss: 0.3212 - accuracy: 0.8599
Epoch 35/100
25/25 [==============================] - 0s 1ms/step - loss: 0.3165 - accuracy: 0.8781
Epoch 36/100
25/25 [==============================] - 0s 1ms/step - loss: 0.3112 - accuracy: 0.8677
Epoch 37/100
25/25 [==============================] - 0s 1ms/step - loss: 0.3098 - accuracy: 0.8742
Epoch 38/100
25/25 [==============================] - 0s 2ms/step - loss: 0.3064 - accuracy: 0.8651
Epoch 39/100
25/25 [==============================] - 0s 1ms/step - loss: 0.2876 - accuracy: 0.8807
Epoch 40/100
25/25 [==============================] - 0s 1ms/step - loss: 0.2984 - accuracy: 0.8664
Epoch 41/100
25/25 [==============================] - 0s 1ms/step - loss: 0.3104 - accuracy: 0.8677
Epoch 42/100
25/25 [==============================] - 0s 2ms/step - loss: 0.2751 - accuracy: 0.8820
Epoch 43/100
25/25 [==============================] - 0s 1ms/step - loss: 0.3063 - accuracy: 0.8716
Epoch 44/100
25/25 [==============================] - 0s 1ms/step - loss: 0.2880 - accuracy: 0.8898
Epoch 45/100
25/25 [==============================] - 0s 1ms/step - loss: 0.3094 - accuracy: 0.8768
Epoch 46/100
25/25 [==============================] - 0s 1ms/step - loss: 0.3185 - accuracy: 0.8651
Epoch 47/100
25/25 [==============================] - 0s 2ms/step - loss: 0.3137 - accuracy: 0.8677
Epoch 48/100
25/25 [==============================] - 0s 1ms/step - loss: 0.2852 - accuracy: 0.8898
Epoch 49/100
25/25 [==============================] - 0s 1ms/step - loss: 0.3069 - accuracy: 0.8625
Epoch 50/100
25/25 [==============================] - 0s 2ms/step - loss: 0.2988 - accuracy: 0.8768
Epoch 51/100
25/25 [==============================] - 0s 1ms/step - loss: 0.2995 - accuracy: 0.8651
Epoch 52/100
25/25 [==============================] - 0s 2ms/step - loss: 0.3056 - accuracy: 0.8755
Epoch 53/100
25/25 [==============================] - 0s 1ms/step - loss: 0.2867 - accuracy: 0.8872
Epoch 54/100
25/25 [==============================] - 0s 1ms/step - loss: 0.3224 - accuracy: 0.8482
Epoch 55/100
25/25 [==============================] - 0s 1ms/step - loss: 0.3002 - accuracy: 0.8742
Epoch 56/100
25/25 [==============================] - 0s 1ms/step - loss: 0.3157 - accuracy: 0.8599
Epoch 57/100
25/25 [==============================] - 0s 1ms/step - loss: 0.2913 - accuracy: 0.8859
Epoch 58/100
25/25 [==============================] - 0s 1ms/step - loss: 0.2918 - accuracy: 0.8768
Epoch 59/100
25/25 [==============================] - 0s 1ms/step - loss: 0.2912 - accuracy: 0.8729
Epoch 60/100
25/25 [==============================] - 0s 1ms/step - loss: 0.2915 - accuracy: 0.8742
Epoch 61/100
25/25 [==============================] - 0s 1ms/step - loss: 0.2831 - accuracy: 0.8885
Epoch 62/100
25/25 [==============================] - 0s 1ms/step - loss: 0.2721 - accuracy: 0.8872
Epoch 63/100
25/25 [==============================] - 0s 1ms/step - loss: 0.2827 - accuracy: 0.8755
Epoch 64/100
25/25 [==============================] - 0s 1ms/step - loss: 0.2793 - accuracy: 0.8833
Epoch 65/100
25/25 [==============================] - 0s 1ms/step - loss: 0.2670 - accuracy: 0.8703
Epoch 66/100
25/25 [==============================] - 0s 2ms/step - loss: 0.2811 - accuracy: 0.8794
Epoch 67/100
25/25 [==============================] - 0s 2ms/step - loss: 0.2808 - accuracy: 0.8794
Epoch 68/100
25/25 [==============================] - 0s 1ms/step - loss: 0.2795 - accuracy: 0.8833
Epoch 69/100
25/25 [==============================] - 0s 1ms/step - loss: 0.2863 - accuracy: 0.8820
Epoch 70/100
25/25 [==============================] - 0s 1ms/step - loss: 0.2831 - accuracy: 0.8923
Epoch 71/100
25/25 [==============================] - 0s 1ms/step - loss: 0.3008 - accuracy: 0.8755
Epoch 72/100
25/25 [==============================] - 0s 1ms/step - loss: 0.2706 - accuracy: 0.8807
Epoch 73/100
25/25 [==============================] - 0s 1ms/step - loss: 0.2914 - accuracy: 0.8768
Epoch 74/100
25/25 [==============================] - 0s 1ms/step - loss: 0.2818 - accuracy: 0.8742
Epoch 75/100
25/25 [==============================] - 0s 1ms/step - loss: 0.2664 - accuracy: 0.8872
Epoch 76/100
25/25 [==============================] - 0s 1ms/step - loss: 0.2924 - accuracy: 0.8846
Epoch 77/100
25/25 [==============================] - 0s 2ms/step - loss: 0.2764 - accuracy: 0.8885
Epoch 78/100
25/25 [==============================] - 0s 1ms/step - loss: 0.2585 - accuracy: 0.8988
Epoch 79/100
25/25 [==============================] - 0s 1ms/step - loss: 0.2667 - accuracy: 0.8898
Epoch 80/100
25/25 [==============================] - 0s 2ms/step - loss: 0.2914 - accuracy: 0.8794
Epoch 81/100
25/25 [==============================] - 0s 2ms/step - loss: 0.2637 - accuracy: 0.8807
Epoch 82/100
25/25 [==============================] - 0s 2ms/step - loss: 0.2816 - accuracy: 0.8859
Epoch 83/100
25/25 [==============================] - 0s 2ms/step - loss: 0.2770 - accuracy: 0.8742
Epoch 84/100
25/25 [==============================] - 0s 2ms/step - loss: 0.2794 - accuracy: 0.8729
Epoch 85/100
25/25 [==============================] - 0s 1ms/step - loss: 0.2687 - accuracy: 0.8949
Epoch 86/100
25/25 [==============================] - 0s 2ms/step - loss: 0.2887 - accuracy: 0.8742
Epoch 87/100
25/25 [==============================] - 0s 1ms/step - loss: 0.3053 - accuracy: 0.8690
Epoch 88/100
25/25 [==============================] - 0s 1ms/step - loss: 0.2898 - accuracy: 0.8703
Epoch 89/100
25/25 [==============================] - 0s 1ms/step - loss: 0.2783 - accuracy: 0.8781
Epoch 90/100
25/25 [==============================] - 0s 1ms/step - loss: 0.3026 - accuracy: 0.8742
Epoch 91/100
25/25 [==============================] - 0s 1ms/step - loss: 0.3071 - accuracy: 0.8768
Epoch 92/100
25/25 [==============================] - 0s 1ms/step - loss: 0.2948 - accuracy: 0.8651
Epoch 93/100
25/25 [==============================] - 0s 1ms/step - loss: 0.2886 - accuracy: 0.8807
Epoch 94/100
25/25 [==============================] - 0s 1ms/step - loss: 0.2883 - accuracy: 0.8742
Epoch 95/100
25/25 [==============================] - 0s 1ms/step - loss: 0.3077 - accuracy: 0.8755
Epoch 96/100
25/25 [==============================] - 0s 1ms/step - loss: 0.2973 - accuracy: 0.8794
Epoch 97/100
25/25 [==============================] - 0s 1ms/step - loss: 0.2920 - accuracy: 0.8846
Epoch 98/100
25/25 [==============================] - 0s 1ms/step - loss: 0.2876 - accuracy: 0.8677
Epoch 99/100
25/25 [==============================] - 0s 1ms/step - loss: 0.3046 - accuracy: 0.8677
Epoch 100/100
25/25 [==============================] - 0s 1ms/step - loss: 0.2898 - accuracy: 0.8703

In [26]:
loss , acc = model.evaluate(x_test , y_test)
acc

7/7 [==============================] - 0s 1ms/step - loss: 0.3508 - accuracy: 0.8394

0.8393782377243042

In [27]:
from sklearn.ensemble import RandomForestClassifier
RandomForestClassifier().fit(x_train , y_train).score(x_test , y_test)

0.844559585492228

El siguiente modelo se uso para la primera prediccion

In [28]:
X_encod = df_encoded.drop('Nivel de Adaptación' , axis = 1)
y_encod = df_encoded['Nivel de Adaptación']
x_train_encod , x_test_encod , y_train_encod , y_test_encod = train_test_split(X_encod , y_encod , test_size = 0.2 , random_state = 42)
model_encode = tf.keras.models.Sequential([
    tf.keras.layers.InputLayer(input_shape = x_train_encod.shape[1:]),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.Dense(100 , activation = 'relu'),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.Dense(100 , activation = 'relu'),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.Dense(3 , activation = 'softmax')
])

# Compilar el modelo
model_encode.compile(loss='sparse_categorical_crossentropy', optimizer=tf.keras.optimizers.Adam(learning_rate=0.001), metrics=['accuracy'])

# Entrenar el modelo con callbacks
callback = tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)
history = model_encode.fit(x_train_encod, y_train_encod, epochs=100, validation_split=0.2, batch_size=64, callbacks=[callback])

# Evaluar el modelo en el conjunto de test
test_loss, test_accuracy = model_encode.evaluate(x_test_encod, y_test_encod)
print(f'Test accuracy: {test_accuracy}')

Epoch 1/100
10/10 [==============================] - 1s 20ms/step - loss: 1.1483 - accuracy: 0.5000 - val_loss: 1.0915 - val_accuracy: 0.3935
Epoch 2/100
10/10 [==============================] - 0s 4ms/step - loss: 0.8013 - accuracy: 0.6932 - val_loss: 1.0664 - val_accuracy: 0.4516
Epoch 3/100
10/10 [==============================] - 0s 4ms/step - loss: 0.6567 - accuracy: 0.7695 - val_loss: 1.0373 - val_accuracy: 0.4839
Epoch 4/100
10/10 [==============================] - 0s 4ms/step - loss: 0.6225 - accuracy: 0.7727 - val_loss: 1.0031 - val_accuracy: 0.5097
Epoch 5/100
10/10 [==============================] - 0s 4ms/step - loss: 0.5422 - accuracy: 0.8101 - val_loss: 0.9905 - val_accuracy: 0.5161
Epoch 6/100
10/10 [==============================] - 0s 4ms/step - loss: 0.5271 - accuracy: 0.8133 - val_loss: 0.9851 - val_accuracy: 0.5161
Epoch 7/100
10/10 [==============================] - 0s 4ms/step - loss: 0.4823 - accuracy: 0.8247 - val_loss: 0.9737 - val_accuracy: 0.5161
Epoch 8/100
10/10 [==============================] - 0s 4ms/step - loss: 0.4658 - accuracy: 0.8425 - val_loss: 0.9552 - val_accuracy: 0.5161
Epoch 9/100
10/10 [==============================] - 0s 4ms/step - loss: 0.4246 - accuracy: 0.8393 - val_loss: 0.9459 - val_accuracy: 0.5161
Epoch 10/100
10/10 [==============================] - 0s 4ms/step - loss: 0.4169 - accuracy: 0.8442 - val_loss: 0.9388 - val_accuracy: 0.5161
Epoch 11/100
10/10 [==============================] - 0s 4ms/step - loss: 0.4037 - accuracy: 0.8571 - val_loss: 0.9471 - val_accuracy: 0.5161
Epoch 12/100
10/10 [==============================] - 0s 4ms/step - loss: 0.3874 - accuracy: 0.8653 - val_loss: 0.9346 - val_accuracy: 0.5419
Epoch 13/100
10/10 [==============================] - 0s 4ms/step - loss: 0.3624 - accuracy: 0.8588 - val_loss: 0.9266 - val_accuracy: 0.5548
Epoch 14/100
10/10 [==============================] - 0s 4ms/step - loss: 0.3563 - accuracy: 0.8831 - val_loss: 0.9138 - val_accuracy: 0.5742
Epoch 15/100
10/10 [==============================] - 0s 4ms/step - loss: 0.3438 - accuracy: 0.8653 - val_loss: 0.8908 - val_accuracy: 0.5935
Epoch 16/100
10/10 [==============================] - 0s 4ms/step - loss: 0.3451 - accuracy: 0.8799 - val_loss: 0.8640 - val_accuracy: 0.6000
Epoch 17/100
10/10 [==============================] - 0s 6ms/step - loss: 0.3273 - accuracy: 0.8734 - val_loss: 0.8565 - val_accuracy: 0.6000
Epoch 18/100
10/10 [==============================] - 0s 5ms/step - loss: 0.3235 - accuracy: 0.8782 - val_loss: 0.8300 - val_accuracy: 0.6065
Epoch 19/100
10/10 [==============================] - 0s 4ms/step - loss: 0.3274 - accuracy: 0.8734 - val_loss: 0.8019 - val_accuracy: 0.6129
Epoch 20/100
10/10 [==============================] - 0s 4ms/step - loss: 0.3232 - accuracy: 0.8636 - val_loss: 0.7717 - val_accuracy: 0.6387
Epoch 21/100
10/10 [==============================] - 0s 4ms/step - loss: 0.3020 - accuracy: 0.8831 - val_loss: 0.7517 - val_accuracy: 0.6387
Epoch 22/100
10/10 [==============================] - 0s 4ms/step - loss: 0.3353 - accuracy: 0.8653 - val_loss: 0.7298 - val_accuracy: 0.6387
Epoch 23/100
10/10 [==============================] - 0s 4ms/step - loss: 0.2875 - accuracy: 0.8766 - val_loss: 0.6780 - val_accuracy: 0.6516
Epoch 24/100
10/10 [==============================] - 0s 4ms/step - loss: 0.2912 - accuracy: 0.8831 - val_loss: 0.6678 - val_accuracy: 0.6581
Epoch 25/100
10/10 [==============================] - 0s 5ms/step - loss: 0.2918 - accuracy: 0.8864 - val_loss: 0.6558 - val_accuracy: 0.6645
Epoch 26/100
10/10 [==============================] - 0s 5ms/step - loss: 0.2938 - accuracy: 0.8864 - val_loss: 0.6418 - val_accuracy: 0.6774
Epoch 27/100
10/10 [==============================] - 0s 5ms/step - loss: 0.2885 - accuracy: 0.8912 - val_loss: 0.5968 - val_accuracy: 0.6968
Epoch 28/100
10/10 [==============================] - 0s 4ms/step - loss: 0.2885 - accuracy: 0.8945 - val_loss: 0.5785 - val_accuracy: 0.7290
Epoch 29/100
10/10 [==============================] - 0s 5ms/step - loss: 0.2847 - accuracy: 0.8815 - val_loss: 0.5573 - val_accuracy: 0.7677
Epoch 30/100
10/10 [==============================] - 0s 4ms/step - loss: 0.2811 - accuracy: 0.8815 - val_loss: 0.5248 - val_accuracy: 0.7871
Epoch 31/100
10/10 [==============================] - 0s 4ms/step - loss: 0.2596 - accuracy: 0.8977 - val_loss: 0.5343 - val_accuracy: 0.7871
Epoch 32/100
10/10 [==============================] - 0s 5ms/step - loss: 0.2616 - accuracy: 0.8912 - val_loss: 0.5213 - val_accuracy: 0.7871
Epoch 33/100
10/10 [==============================] - 0s 5ms/step - loss: 0.2681 - accuracy: 0.8880 - val_loss: 0.4918 - val_accuracy: 0.8065
Epoch 34/100
10/10 [==============================] - 0s 5ms/step - loss: 0.2724 - accuracy: 0.8912 - val_loss: 0.4896 - val_accuracy: 0.8129
Epoch 35/100
10/10 [==============================] - 0s 5ms/step - loss: 0.2731 - accuracy: 0.8880 - val_loss: 0.4853 - val_accuracy: 0.8065
Epoch 36/100
10/10 [==============================] - 0s 4ms/step - loss: 0.2589 - accuracy: 0.8864 - val_loss: 0.4807 - val_accuracy: 0.8065
Epoch 37/100
10/10 [==============================] - 0s 4ms/step - loss: 0.2674 - accuracy: 0.8994 - val_loss: 0.4573 - val_accuracy: 0.8065
Epoch 38/100
10/10 [==============================] - 0s 5ms/step - loss: 0.2665 - accuracy: 0.8896 - val_loss: 0.4544 - val_accuracy: 0.8323
Epoch 39/100
10/10 [==============================] - 0s 5ms/step - loss: 0.2514 - accuracy: 0.8977 - val_loss: 0.4612 - val_accuracy: 0.8194
Epoch 40/100
10/10 [==============================] - 0s 4ms/step - loss: 0.2566 - accuracy: 0.8896 - val_loss: 0.4635 - val_accuracy: 0.8194
Epoch 41/100
10/10 [==============================] - 0s 4ms/step - loss: 0.2672 - accuracy: 0.8831 - val_loss: 0.4563 - val_accuracy: 0.8000
Epoch 42/100
10/10 [==============================] - 0s 5ms/step - loss: 0.2600 - accuracy: 0.8864 - val_loss: 0.4597 - val_accuracy: 0.8194
Epoch 43/100
10/10 [==============================] - 0s 4ms/step - loss: 0.2539 - accuracy: 0.8961 - val_loss: 0.4598 - val_accuracy: 0.8129
Epoch 44/100
10/10 [==============================] - 0s 4ms/step - loss: 0.2722 - accuracy: 0.8847 - val_loss: 0.4555 - val_accuracy: 0.8258
Epoch 45/100
10/10 [==============================] - 0s 4ms/step - loss: 0.2559 - accuracy: 0.8961 - val_loss: 0.4326 - val_accuracy: 0.8387
Epoch 46/100
10/10 [==============================] - 0s 5ms/step - loss: 0.2648 - accuracy: 0.8929 - val_loss: 0.4314 - val_accuracy: 0.8194
Epoch 47/100
10/10 [==============================] - 0s 4ms/step - loss: 0.2459 - accuracy: 0.9075 - val_loss: 0.4507 - val_accuracy: 0.8258
Epoch 48/100
10/10 [==============================] - 0s 4ms/step - loss: 0.2393 - accuracy: 0.8896 - val_loss: 0.4395 - val_accuracy: 0.8194
Epoch 49/100
10/10 [==============================] - 0s 4ms/step - loss: 0.2455 - accuracy: 0.8945 - val_loss: 0.4412 - val_accuracy: 0.8000
Epoch 50/100
10/10 [==============================] - 0s 5ms/step - loss: 0.2606 - accuracy: 0.8847 - val_loss: 0.4287 - val_accuracy: 0.8000
Epoch 51/100
10/10 [==============================] - 0s 5ms/step - loss: 0.2498 - accuracy: 0.8896 - val_loss: 0.4639 - val_accuracy: 0.8323
Epoch 52/100
10/10 [==============================] - 0s 5ms/step - loss: 0.2375 - accuracy: 0.9010 - val_loss: 0.4618 - val_accuracy: 0.8129
Epoch 53/100
10/10 [==============================] - 0s 5ms/step - loss: 0.2484 - accuracy: 0.9010 - val_loss: 0.4389 - val_accuracy: 0.8194
Epoch 54/100
10/10 [==============================] - 0s 4ms/step - loss: 0.2469 - accuracy: 0.8815 - val_loss: 0.4438 - val_accuracy: 0.8129
Epoch 55/100
10/10 [==============================] - 0s 4ms/step - loss: 0.2506 - accuracy: 0.8912 - val_loss: 0.4544 - val_accuracy: 0.8387
Epoch 56/100
10/10 [==============================] - 0s 4ms/step - loss: 0.2376 - accuracy: 0.8929 - val_loss: 0.4564 - val_accuracy: 0.7935
Epoch 57/100
10/10 [==============================] - 0s 4ms/step - loss: 0.2430 - accuracy: 0.9058 - val_loss: 0.4542 - val_accuracy: 0.8129
Epoch 58/100
10/10 [==============================] - 0s 4ms/step - loss: 0.2568 - accuracy: 0.8799 - val_loss: 0.4787 - val_accuracy: 0.8129
Epoch 59/100
10/10 [==============================] - 0s 4ms/step - loss: 0.2585 - accuracy: 0.8847 - val_loss: 0.4407 - val_accuracy: 0.8258
Epoch 60/100
10/10 [==============================] - 0s 6ms/step - loss: 0.2714 - accuracy: 0.8815 - val_loss: 0.4482 - val_accuracy: 0.8000
7/7 [==============================] - 0s 2ms/step - loss: 0.3918 - accuracy: 0.8446
Test accuracy: 0.8445596098899841

In [29]:
loss_encod , acc_encod = model_encode.evaluate(x_test_encod , y_test_encod)
acc_encod

7/7 [==============================] - 0s 2ms/step - loss: 0.3918 - accuracy: 0.8446

0.8445596098899841

In [30]:
RandomForestClassifier().fit(x_train_encod , y_train_encod).score(x_test_encod , y_test_encod)

0.8497409326424871

In [31]:
data_test = pd.read_csv("submission-ds.csv")

In [32]:
data_test['Edad'] = data_test['Edad'].apply(convertir_mes_a_numero)
data_test['Duración de la Clase'] = data_test['Duración de la Clase'].apply(convertir_mes_a_numero)
data_test = data_test.apply(LabelEncoder().fit_transform)

In [33]:

data_test

,Tipo de Red,Estudiante de Tecnología,Nivel de Educación,Vive en Ciudad,Tipo de Instituto,Edad,Dispositivo,Tipo de Internet,Situación Financiera,Género,Duración de la Clase
0,1,0,0,0,1,3,1,0,1,1,1
1,2,0,0,0,0,2,1,1,2,0,1
2,2,0,2,1,1,3,1,0,2,1,0
3,1,1,2,0,1,3,1,0,2,1,1
4,1,0,1,0,1,5,1,0,2,0,0
...,...,...,...,...,...,...,...,...,...,...,...
236,2,0,1,1,0,0,1,1,2,0,1
237,2,0,1,1,0,0,1,0,2,0,1
238,2,0,1,1,0,1,1,0,2,1,1
239,2,0,1,1,1,2,1,1,2,1,1
240,1,0,1,1,0,1,1,0,2,1,1

In [34]:
predictions = model_encode.predict(data_test)

# Las predicciones son probabilidades para cada clase, puedes obtener la clase predicha usando argmax
predicted_classes = predictions.argmax(axis=1)

# Ahora 'predicted_classes' contiene las clases predichas para tus datos de prueba
print(predicted_classes)

8/8 [==============================] - 0s 1ms/step
[2 1 1 1 1 0 1 2 1 1 1 2 2 1 1 2 2 2 2 2 1 2 2 2 2 1 1 1 1 2 2 1 0 2 1 1 1
 2 2 1 2 1 1 1 2 2 2 1 1 2 2 1 2 1 2 2 1 2 2 1 2 1 1 2 1 2 1 1 1 2 1 2 1 2
 1 2 2 1 2 2 2 2 1 2 2 0 2 1 2 2 2 2 2 2 2 2 2 2 1 1 2 0 1 2 2 1 1 2 2 2 2
 1 2 1 1 2 2 2 0 1 2 1 2 1 2 1 2 1 0 1 2 1 0 2 2 2 1 1 1 2 2 2 2 1 2 1 2 2
 0 2 2 1 2 2 2 2 2 2 2 2 1 0 0 2 1 2 0 2 1 2 0 2 2 1 1 2 1 1 2 1 2 1 2 1 1
 2 1 2 2 2 2 2 1 2 2 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 1 1 2 2 1 2 2 1 2 2 2 1
 1 1 2 2 2 1 2 2 2 1 0 2 1 1 2 2 2 2 2]

In [35]:
data_test['Nivel de Adaptación'] = predicted_classes
data_test

,Tipo de Red,Estudiante de Tecnología,Nivel de Educación,Vive en Ciudad,Tipo de Instituto,Edad,Dispositivo,Tipo de Internet,Situación Financiera,Género,Duración de la Clase,Nivel de Adaptación
0,1,0,0,0,1,3,1,0,1,1,1,2
1,2,0,0,0,0,2,1,1,2,0,1,1
2,2,0,2,1,1,3,1,0,2,1,0,1
3,1,1,2,0,1,3,1,0,2,1,1,1
4,1,0,1,0,1,5,1,0,2,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
236,2,0,1,1,0,0,1,1,2,0,1,2
237,2,0,1,1,0,0,1,0,2,0,1,2
238,2,0,1,1,0,1,1,0,2,1,1,2
239,2,0,1,1,1,2,1,1,2,1,1,2
240,1,0,1,1,0,1,1,0,2,1,1,2

In [36]:
resultados_prediccion = pd.DataFrame({
    'id': range(1, len(predicted_classes) + 1),
    'Nivel de Adaptación': predicted_classes
})
resultados_prediccion['Nivel de Adaptación'] = resultados_prediccion['Nivel de Adaptación'].map({0: 'Bajo', 1: 'Moderado', 2: 'Alto'})

# Mostrar el DataFrame con las etiquetas mapeadas
print(resultados_prediccion)

      id Nivel de Adaptación
0      1                Alto
1      2            Moderado
2      3            Moderado
3      4            Moderado
4      5            Moderado
..   ...                 ...
236  237                Alto
237  238                Alto
238  239                Alto
239  240                Alto
240  241                Alto

[241 rows x 2 columns]

In [37]:
resultados_prediccion.to_csv('resultados_prediccion.csv', index=False)

In [39]:

accuracy = accuracy_score(y_encod, predicted_classes)

# Muestra la precisión
print(f'Precisión: {accuracy}')

ValueError: Found input variables with inconsistent numbers of samples: [964, 241]