In [130]:
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
from scipy.stats import chi2_contingency

In [131]:
data = pd.read_csv("training-ds.csv")
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 964 entries, 0 to 963
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Tipo de Red               964 non-null    object
 1   Estudiante de Tecnología  964 non-null    object
 2   Nivel de Educación        964 non-null    object
 3   Vive en Ciudad            964 non-null    object
 4   Tipo de Instituto         964 non-null    object
 5   Edad                      964 non-null    object
 6   Dispositivo               964 non-null    object
 7   Tipo de Internet          964 non-null    object
 8   Situación Financiera      964 non-null    object
 9   Género                    964 non-null    object
 10  Duración de la Clase      964 non-null    object
 11  Nivel de Adaptación       964 non-null    object
dtypes: object(12)
memory usage: 90.5+ KB
None

In [132]:
data.shape

(964, 12)

In [133]:
def convertir_mes_a_numero(fecha):
    if len(fecha) == 5 and fecha[1] == '-' and fecha[2:].isdigit():
        return fecha  
    
    meses = {
        'Jan': '1', 'Feb': '2', 'Mar': '3', 'Apr': '4',
        'May': '5', 'Jun': '6', 'Jul': '7', 'Aug': '8',
        'Sep': '9', 'Oct': '10', 'Nov': '11', 'Dec': '12'
    }
    if len(fecha) == 6 and fecha[2] == '-' and fecha[:2].isdigit():
        numero_mes = meses.get(fecha[3:])
        if numero_mes:
            return f"{int(fecha[:2])}-{numero_mes.zfill(2)}"
    
    partes = fecha.split('-')
    numero_mes = meses.get(partes[0])
    if numero_mes:
        return f"{numero_mes}-{partes[1]}"
    else:
        return fecha 

data['Edad'] = data['Edad'].apply(convertir_mes_a_numero)
data['Duración de la Clase'] = data['Duración de la Clase'].apply(convertir_mes_a_numero)

In [134]:
data

,Tipo de Red,Estudiante de Tecnología,Nivel de Educación,Vive en Ciudad,Tipo de Instituto,Edad,Dispositivo,Tipo de Internet,Situación Financiera,Género,Duración de la Clase,Nivel de Adaptación
0,3G,Si,Universidad,Si,Privado,21-25,Computadora,Wifi,Media,Masculino,3-06,Bajo
1,3G,No,Escuela,Si,Privado,11-15,Smartphone,Compra Megas,Media,Femenino,1-03,Moderado
2,3G,Si,Universidad,Si,Privado,21-25,Smartphone,Compra Megas,Mala,Masculino,1-03,Bajo
3,3G,Si,Escuela,Si,Privado,11-15,Smartphone,Compra Megas,Media,Masculino,1-03,Moderado
4,4G,Si,Universidad,Si,Privado,21-25,Computadora,Wifi,Buena,Masculino,1-03,Alto
...,...,...,...,...,...,...,...,...,...,...,...,...
959,3G,No,Universidad,Si,Privado,21-25,Smartphone,Compra Megas,Media,Masculino,1-03,Moderado
960,3G,No,Escuela,Si,Privado,11-15,Smartphone,Compra Megas,Media,Femenino,1-03,Moderado
961,4G,No,Universidad,Si,Público,21-25,Smartphone,Compra Megas,Media,Masculino,0,Bajo
962,3G,No,Universidad,Si,Privado,21-25,Smartphone,Compra Megas,Media,Masculino,1-03,Moderado
963,4G,No,Escuela,Si,Privado,1-05,Smartphone,Compra Megas,Media,Femenino,1-03,Moderado

In [135]:
display(data.dtypes)

Tipo de Red                 object
Estudiante de Tecnología    object
Nivel de Educación          object
Vive en Ciudad              object
Tipo de Instituto           object
Edad                        object
Dispositivo                 object
Tipo de Internet            object
Situación Financiera        object
Género                      object
Duración de la Clase        object
Nivel de Adaptación         object
dtype: object

In [136]:
def print_unique_values(data_frame, dtype='object'):
    for column in data_frame.columns:
        if data_frame[column].dtype == dtype:
            print(f'{column}: {list(data_frame[column].unique())}')


print_unique_values(data)

Tipo de Red: ['3G', '4G', '2G']
Estudiante de Tecnología: ['Si', 'No']
Nivel de Educación: ['Universidad', 'Escuela', 'Colegio']
Vive en Ciudad: ['Si', 'No']
Tipo de Instituto: ['Privado', 'Público']
Edad: ['21-25', '11-15', '16-20', '26-30', '1-05', '6-10']
Dispositivo: ['Computadora', 'Smartphone', 'Tableta']
Tipo de Internet: ['Wifi', 'Compra Megas']
Situación Financiera: ['Media', 'Mala', 'Buena']
Género: ['Masculino', 'Femenino']
Duración de la Clase: ['3-06', '1-03', '0']
Nivel de Adaptación: ['Bajo', 'Moderado', 'Alto']

In [137]:
data_transform= data
data_transform = pd.get_dummies(data, columns=[ 'Estudiante de Tecnología', "Vive en Ciudad",'Tipo de Instituto','Tipo de Internet','Género'])
#display(data_transform.head(100))

In [138]:
# Crear el DataFrame
df = pd.DataFrame(data)
# Codificar las variables categóricas a números usando LabelEncoder
df_encoded = df.apply(LabelEncoder().fit_transform)
# Dividir el DataFrame en variables predictoras (X) y la variable objetivo (y)
X = df_encoded.drop('Nivel de Adaptación', axis=1)
y = df_encoded['Nivel de Adaptación']
# Inicializar el clasificador RandomForestClassifier
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)
# Entrenar el modelo
rf_classifier.fit(X, y)
# Obtener la importancia de las características
feature_importances = rf_classifier.feature_importances_
# Crear un DataFrame con las importancias de las características
importance_df = pd.DataFrame({'Feature': X.columns, 'Importance': feature_importances})
importance_df = importance_df.sort_values(by='Importance', ascending=False)
# Mostrar las características más importantes
importance_df

                     Feature  Importance
10      Duración de la Clase    0.181185
8       Situación Financiera    0.132298
5                       Edad    0.130287
9                     Género    0.098232
4          Tipo de Instituto    0.075108
2         Nivel de Educación    0.073862
0                Tipo de Red    0.071743
3             Vive en Ciudad    0.069197
7           Tipo de Internet    0.064026
1   Estudiante de Tecnología    0.053043
6                Dispositivo    0.051019

In [139]:
correlation_nivel_adaptacion = df_encoded.corr(method='pearson')['Nivel de Adaptación']
# Correlación con método pearson en orden ascendente
display((correlation_nivel_adaptacion[np.argsort(correlation_nivel_adaptacion, axis=0)[::-1]]).head(11))

Nivel de Adaptación         1.000000
Situación Financiera        0.258934
Duración de la Clase        0.209937
Vive en Ciudad              0.104525
Dispositivo                 0.066690
Estudiante de Tecnología    0.044715
Tipo de Red                 0.021874
Nivel de Educación         -0.015269
Género                     -0.042976
Tipo de Internet           -0.069489
Tipo de Instituto          -0.172572
Name: Nivel de Adaptación, dtype: float64

In [140]:
def print_zeros_values(data_frame):
    for column in data_frame.columns:
        print (f'{column}: {sum(data_frame[column] == 0)}')

print_zeros_values(data_transform)

Tipo de Red: 0
Nivel de Educación: 0
Edad: 0
Dispositivo: 0
Situación Financiera: 0
Duración de la Clase: 0
Nivel de Adaptación: 0
Estudiante de Tecnología_No: 243
Estudiante de Tecnología_Si: 721
Vive en Ciudad_No: 756
Vive en Ciudad_Si: 208
Tipo de Instituto_Privado: 302
Tipo de Instituto_Público: 662
Tipo de Internet_Compra Megas: 413
Tipo de Internet_Wifi: 551
Género_Femenino: 532
Género_Masculino: 432

In [141]:
data_transform = data_transform.rename(columns={'Nivel de Adaptación':'Nivel de Adaptacion'})
data_transform.insert(loc=len(data_transform.columns)-1, column='Nivel de Adaptacion', value=data_transform.pop('Nivel de Adaptacion'))

In [142]:
correlation_level_adaption = data_transform.corrwith(data_transform['Nivel de Adaptacion'], method='kendall')
# Ordenar por valor absoluto en orden descendente
correlation_level_adaption = correlation_level_adaption.abs().sort_values(ascending=False)
print(correlation_level_adaption.head(11))

Tipo de Instituto_Privado        0.205034
Tipo de Instituto_Público        0.205034
Vive en Ciudad_No                0.136796
Vive en Ciudad_Si                0.136796
Estudiante de Tecnología_No      0.064079
Estudiante de Tecnología_Si      0.064079
Tipo de Internet_Compra Megas    0.049212
Tipo de Internet_Wifi            0.049212
Género_Femenino                  0.024113
Género_Masculino                 0.024113
dtype: float64

C:\Users\miky1\AppData\Local\Temp\ipykernel_23960\2588461948.py:1: FutureWarning: The default value of numeric_only in DataFrame.corrwith is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  correlation_level_adaption = data_transform.corrwith(data_transform['Nivel de Adaptacion'], method='kendall')

In [143]:
correlation_level_adaption = data.corrwith(data['Nivel de Adaptación'], method='kendall')
# Ordenar por valor absoluto en orden descendente
print(correlation_level_adaption)

Series([], dtype: float64)

C:\Users\miky1\AppData\Local\Temp\ipykernel_23960\1892343149.py:1: FutureWarning: The default value of numeric_only in DataFrame.corrwith is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  correlation_level_adaption = data.corrwith(data['Nivel de Adaptación'], method='kendall')

In [144]:

df_chi = pd.DataFrame(data)

# Obtener todas las columnas categóricas (excluyendo la columna 'Nivel de Adaptación')
categorical_columns = df_chi.select_dtypes(include=['object']).columns.tolist()
categorical_columns.remove('Nivel de Adaptación')

# Realizar la prueba de Chi-cuadrado para cada columna categórica
results = {}
for column in categorical_columns:
    contingency_table = pd.crosstab(df_chi['Nivel de Adaptación'], df_chi[column])
    chi2, p, _, _ = chi2_contingency(contingency_table)
    results[column] = {'Chi-cuadrado': chi2, 'Valor p': p}

# Mostrar los resultados
for column, result in results.items():
    print(f"Variable: {column}")
    print(f"Chi-cuadrado: {result['Chi-cuadrado']}")
    print(f"Valor p: {result['Valor p']}")
    print("---------")

Variable: Tipo de Red
Chi-cuadrado: 22.416899468049962
Valor p: 0.00016553607337707634
---------
Variable: Estudiante de Tecnología
Chi-cuadrado: 18.071856218207742
Valor p: 0.00011905462826913621
---------
Variable: Nivel de Educación
Chi-cuadrado: 34.12387833220294
Valor p: 7.028430339688034e-07
---------
Variable: Vive en Ciudad
Chi-cuadrado: 58.93948394141377
Valor p: 1.590207066435886e-13
---------
Variable: Tipo de Instituto
Chi-cuadrado: 86.2495346195265
Valor p: 1.8670309785740592e-19
---------
Variable: Edad
Chi-cuadrado: 99.38765927838557
Valor p: 7.225920028459192e-17
---------
Variable: Dispositivo
Chi-cuadrado: 43.667029513202095
Valor p: 7.523116516226196e-09
---------
Variable: Tipo de Internet
Chi-cuadrado: 14.865597060186293
Valor p: 0.000591529779493374
---------
Variable: Situación Financiera
Chi-cuadrado: 169.29098707058372
Valor p: 1.4846830691108703e-35
---------
Variable: Género
Chi-cuadrado: 11.77281525381296
Valor p: 0.0027769345850669797
---------
Variable: Duración de la Clase
Chi-cuadrado: 175.07187246811478
Valor p: 8.526003556326326e-37
---------

In [145]:
significative_columns = [column for column, result in results.items() if result['Valor p'] < 0.05]

# Utilizar estas columnas significativas para entrenar tu red neuronal
# X serían tus datos con estas columnas seleccionadas y 'Nivel de Adaptación' sería tu variable objetivo
X = df_chi[significative_columns]
y = df_chi['Nivel de Adaptación']

In [146]:
data2 = data
data2

,Tipo de Red,Estudiante de Tecnología,Nivel de Educación,Vive en Ciudad,Tipo de Instituto,Edad,Dispositivo,Tipo de Internet,Situación Financiera,Género,Duración de la Clase,Nivel de Adaptación
0,3G,Si,Universidad,Si,Privado,21-25,Computadora,Wifi,Media,Masculino,3-06,Bajo
1,3G,No,Escuela,Si,Privado,11-15,Smartphone,Compra Megas,Media,Femenino,1-03,Moderado
2,3G,Si,Universidad,Si,Privado,21-25,Smartphone,Compra Megas,Mala,Masculino,1-03,Bajo
3,3G,Si,Escuela,Si,Privado,11-15,Smartphone,Compra Megas,Media,Masculino,1-03,Moderado
4,4G,Si,Universidad,Si,Privado,21-25,Computadora,Wifi,Buena,Masculino,1-03,Alto
...,...,...,...,...,...,...,...,...,...,...,...,...
959,3G,No,Universidad,Si,Privado,21-25,Smartphone,Compra Megas,Media,Masculino,1-03,Moderado
960,3G,No,Escuela,Si,Privado,11-15,Smartphone,Compra Megas,Media,Femenino,1-03,Moderado
961,4G,No,Universidad,Si,Público,21-25,Smartphone,Compra Megas,Media,Masculino,0,Bajo
962,3G,No,Universidad,Si,Privado,21-25,Smartphone,Compra Megas,Media,Masculino,1-03,Moderado
963,4G,No,Escuela,Si,Privado,1-05,Smartphone,Compra Megas,Media,Femenino,1-03,Moderado

In [147]:
data['Nivel de Adaptación']

0          Bajo
1      Moderado
2          Bajo
3      Moderado
4          Alto
         ...
959    Moderado
960    Moderado
961        Bajo
962    Moderado
963    Moderado
Name: Nivel de Adaptación, Length: 964, dtype: object

In [148]:
#data = data2

In [149]:
# Mapear los valores de la columna 'Nivel de Adaptación' a números
mapping = {'Bajo': 0, 'Moderado': 1, 'Alto': 2}
data['Nivel de Adaptación'] = data['Nivel de Adaptación'].map(mapping)

# Verificar el resultado
print(data['Nivel de Adaptación'])

0      0
1      1
2      0
3      1
4      2
      ..
959    1
960    1
961    0
962    1
963    1
Name: Nivel de Adaptación, Length: 964, dtype: int64

In [150]:
data

,Tipo de Red,Estudiante de Tecnología,Nivel de Educación,Vive en Ciudad,Tipo de Instituto,Edad,Dispositivo,Tipo de Internet,Situación Financiera,Género,Duración de la Clase,Nivel de Adaptación
0,3G,Si,Universidad,Si,Privado,21-25,Computadora,Wifi,Media,Masculino,3-06,0
1,3G,No,Escuela,Si,Privado,11-15,Smartphone,Compra Megas,Media,Femenino,1-03,1
2,3G,Si,Universidad,Si,Privado,21-25,Smartphone,Compra Megas,Mala,Masculino,1-03,0
3,3G,Si,Escuela,Si,Privado,11-15,Smartphone,Compra Megas,Media,Masculino,1-03,1
4,4G,Si,Universidad,Si,Privado,21-25,Computadora,Wifi,Buena,Masculino,1-03,2
...,...,...,...,...,...,...,...,...,...,...,...,...
959,3G,No,Universidad,Si,Privado,21-25,Smartphone,Compra Megas,Media,Masculino,1-03,1
960,3G,No,Escuela,Si,Privado,11-15,Smartphone,Compra Megas,Media,Femenino,1-03,1
961,4G,No,Universidad,Si,Público,21-25,Smartphone,Compra Megas,Media,Masculino,0,0
962,3G,No,Universidad,Si,Privado,21-25,Smartphone,Compra Megas,Media,Masculino,1-03,1
963,4G,No,Escuela,Si,Privado,1-05,Smartphone,Compra Megas,Media,Femenino,1-03,1

In [151]:
x = data.drop('Nivel de Adaptación' , axis = 1)
y = data['Nivel de Adaptación']

In [152]:
x

,Tipo de Red,Estudiante de Tecnología,Nivel de Educación,Vive en Ciudad,Tipo de Instituto,Edad,Dispositivo,Tipo de Internet,Situación Financiera,Género,Duración de la Clase
0,3G,Si,Universidad,Si,Privado,21-25,Computadora,Wifi,Media,Masculino,3-06
1,3G,No,Escuela,Si,Privado,11-15,Smartphone,Compra Megas,Media,Femenino,1-03
2,3G,Si,Universidad,Si,Privado,21-25,Smartphone,Compra Megas,Mala,Masculino,1-03
3,3G,Si,Escuela,Si,Privado,11-15,Smartphone,Compra Megas,Media,Masculino,1-03
4,4G,Si,Universidad,Si,Privado,21-25,Computadora,Wifi,Buena,Masculino,1-03
...,...,...,...,...,...,...,...,...,...,...,...
959,3G,No,Universidad,Si,Privado,21-25,Smartphone,Compra Megas,Media,Masculino,1-03
960,3G,No,Escuela,Si,Privado,11-15,Smartphone,Compra Megas,Media,Femenino,1-03
961,4G,No,Universidad,Si,Público,21-25,Smartphone,Compra Megas,Media,Masculino,0
962,3G,No,Universidad,Si,Privado,21-25,Smartphone,Compra Megas,Media,Masculino,1-03
963,4G,No,Escuela,Si,Privado,1-05,Smartphone,Compra Megas,Media,Femenino,1-03

In [153]:

x_train , x_test , y_train , y_test = train_test_split(pd.get_dummies(x) , y , test_size = 0.2 , random_state = 42)

In [154]:
model = tf.keras.models.Sequential([
    tf.keras.layers.InputLayer(input_shape = x_train.shape[1:]),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.Dense(100 , activation = 'relu'),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.Dense(100 , activation = 'relu'),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.Dense(3 , activation = 'softmax')
])

model.compile(loss = tf.keras.losses.sparse_categorical_crossentropy , optimizer = tf.keras.optimizers.Adam() , metrics = ['accuracy'])

model.fit(x_train , y_train , epochs = 100)

Epoch 1/100

25/25 [==============================] - 3s 4ms/step - loss: 1.0733 - accuracy: 0.5201
Epoch 2/100
25/25 [==============================] - 0s 4ms/step - loss: 0.6763 - accuracy: 0.7276
Epoch 3/100
25/25 [==============================] - 0s 4ms/step - loss: 0.5874 - accuracy: 0.7821
Epoch 4/100
25/25 [==============================] - 0s 4ms/step - loss: 0.5064 - accuracy: 0.8054
Epoch 5/100
25/25 [==============================] - 0s 4ms/step - loss: 0.4760 - accuracy: 0.8405
Epoch 6/100
25/25 [==============================] - 0s 4ms/step - loss: 0.4630 - accuracy: 0.8301
Epoch 7/100
25/25 [==============================] - 0s 4ms/step - loss: 0.4077 - accuracy: 0.8444
Epoch 8/100
25/25 [==============================] - 0s 4ms/step - loss: 0.4116 - accuracy: 0.8418
Epoch 9/100
25/25 [==============================] - 0s 3ms/step - loss: 0.3744 - accuracy: 0.8547
Epoch 10/100
25/25 [==============================] - 0s 3ms/step - loss: 0.3758 - accuracy: 0.8599
Epoch 11/100
25/25 [==============================] - 0s 3ms/step - loss: 0.3667 - accuracy: 0.8677
Epoch 12/100
25/25 [==============================] - 0s 3ms/step - loss: 0.3637 - accuracy: 0.8573
Epoch 13/100
25/25 [==============================] - 0s 3ms/step - loss: 0.3542 - accuracy: 0.8470
Epoch 14/100
25/25 [==============================] - 0s 3ms/step - loss: 0.3473 - accuracy: 0.8677
Epoch 15/100
25/25 [==============================] - 0s 3ms/step - loss: 0.3395 - accuracy: 0.8664
Epoch 16/100
25/25 [==============================] - 0s 3ms/step - loss: 0.3566 - accuracy: 0.8612
Epoch 17/100
25/25 [==============================] - 0s 4ms/step - loss: 0.3192 - accuracy: 0.8729
Epoch 18/100
25/25 [==============================] - 0s 3ms/step - loss: 0.3300 - accuracy: 0.8560
Epoch 19/100
25/25 [==============================] - 0s 3ms/step - loss: 0.3254 - accuracy: 0.8664
Epoch 20/100
25/25 [==============================] - 0s 5ms/step - loss: 0.3238 - accuracy: 0.8768
Epoch 21/100
25/25 [==============================] - 0s 4ms/step - loss: 0.3455 - accuracy: 0.8508
Epoch 22/100
25/25 [==============================] - 0s 3ms/step - loss: 0.3245 - accuracy: 0.8677
Epoch 23/100
25/25 [==============================] - 0s 3ms/step - loss: 0.3222 - accuracy: 0.8794
Epoch 24/100
25/25 [==============================] - 0s 3ms/step - loss: 0.3251 - accuracy: 0.8547
Epoch 25/100
25/25 [==============================] - 0s 3ms/step - loss: 0.3207 - accuracy: 0.8833
Epoch 26/100
25/25 [==============================] - 0s 3ms/step - loss: 0.3031 - accuracy: 0.8781
Epoch 27/100
25/25 [==============================] - 0s 3ms/step - loss: 0.3154 - accuracy: 0.8638
Epoch 28/100
25/25 [==============================] - 0s 3ms/step - loss: 0.3158 - accuracy: 0.8768
Epoch 29/100
25/25 [==============================] - 0s 4ms/step - loss: 0.3240 - accuracy: 0.8586
Epoch 30/100
25/25 [==============================] - 0s 5ms/step - loss: 0.2973 - accuracy: 0.8677
Epoch 31/100
25/25 [==============================] - 0s 5ms/step - loss: 0.2865 - accuracy: 0.8768
Epoch 32/100
25/25 [==============================] - 0s 4ms/step - loss: 0.3109 - accuracy: 0.8651
Epoch 33/100
25/25 [==============================] - 0s 4ms/step - loss: 0.2889 - accuracy: 0.8716
Epoch 34/100
25/25 [==============================] - 0s 3ms/step - loss: 0.3123 - accuracy: 0.8677
Epoch 35/100
25/25 [==============================] - 0s 3ms/step - loss: 0.3041 - accuracy: 0.8729
Epoch 36/100
25/25 [==============================] - 0s 3ms/step - loss: 0.3153 - accuracy: 0.8612
Epoch 37/100
25/25 [==============================] - 0s 5ms/step - loss: 0.2975 - accuracy: 0.8807
Epoch 38/100
25/25 [==============================] - 0s 4ms/step - loss: 0.3037 - accuracy: 0.8755
Epoch 39/100
25/25 [==============================] - 0s 4ms/step - loss: 0.2993 - accuracy: 0.8768
Epoch 40/100
25/25 [==============================] - 0s 3ms/step - loss: 0.2981 - accuracy: 0.8781
Epoch 41/100
25/25 [==============================] - 0s 5ms/step - loss: 0.3145 - accuracy: 0.8755
Epoch 42/100
25/25 [==============================] - 0s 4ms/step - loss: 0.3035 - accuracy: 0.8690
Epoch 43/100
25/25 [==============================] - 0s 4ms/step - loss: 0.2965 - accuracy: 0.8768
Epoch 44/100
25/25 [==============================] - 0s 5ms/step - loss: 0.3061 - accuracy: 0.8742
Epoch 45/100
25/25 [==============================] - 0s 5ms/step - loss: 0.2960 - accuracy: 0.8703
Epoch 46/100
25/25 [==============================] - 0s 5ms/step - loss: 0.3099 - accuracy: 0.8664
Epoch 47/100
25/25 [==============================] - 0s 5ms/step - loss: 0.2932 - accuracy: 0.8807
Epoch 48/100
25/25 [==============================] - 0s 5ms/step - loss: 0.2970 - accuracy: 0.8781
Epoch 49/100
25/25 [==============================] - 0s 4ms/step - loss: 0.3013 - accuracy: 0.8885
Epoch 50/100
25/25 [==============================] - 0s 5ms/step - loss: 0.3027 - accuracy: 0.8625
Epoch 51/100
25/25 [==============================] - 0s 4ms/step - loss: 0.2980 - accuracy: 0.8755
Epoch 52/100
25/25 [==============================] - 0s 5ms/step - loss: 0.3079 - accuracy: 0.8794
Epoch 53/100
25/25 [==============================] - 0s 4ms/step - loss: 0.3066 - accuracy: 0.8677
Epoch 54/100
25/25 [==============================] - 0s 4ms/step - loss: 0.3268 - accuracy: 0.8781
Epoch 55/100
25/25 [==============================] - 0s 5ms/step - loss: 0.3053 - accuracy: 0.8651
Epoch 56/100
25/25 [==============================] - 0s 4ms/step - loss: 0.2939 - accuracy: 0.8729
Epoch 57/100
25/25 [==============================] - 0s 4ms/step - loss: 0.2955 - accuracy: 0.8820
Epoch 58/100
25/25 [==============================] - 0s 4ms/step - loss: 0.3252 - accuracy: 0.8664
Epoch 59/100
25/25 [==============================] - 0s 3ms/step - loss: 0.3099 - accuracy: 0.8664
Epoch 60/100
25/25 [==============================] - 0s 4ms/step - loss: 0.2904 - accuracy: 0.8820
Epoch 61/100
25/25 [==============================] - 0s 5ms/step - loss: 0.2898 - accuracy: 0.8872
Epoch 62/100
25/25 [==============================] - 0s 5ms/step - loss: 0.2977 - accuracy: 0.8651
Epoch 63/100
25/25 [==============================] - 0s 4ms/step - loss: 0.2898 - accuracy: 0.8755
Epoch 64/100
25/25 [==============================] - 0s 4ms/step - loss: 0.3034 - accuracy: 0.8690
Epoch 65/100
25/25 [==============================] - 0s 4ms/step - loss: 0.2880 - accuracy: 0.8664
Epoch 66/100
25/25 [==============================] - 0s 4ms/step - loss: 0.2728 - accuracy: 0.8781
Epoch 67/100
25/25 [==============================] - 0s 3ms/step - loss: 0.2889 - accuracy: 0.8859
Epoch 68/100
25/25 [==============================] - 0s 3ms/step - loss: 0.2888 - accuracy: 0.8833
Epoch 69/100
25/25 [==============================] - 0s 3ms/step - loss: 0.2922 - accuracy: 0.8664
Epoch 70/100
25/25 [==============================] - 0s 4ms/step - loss: 0.2861 - accuracy: 0.8807
Epoch 71/100
25/25 [==============================] - 0s 4ms/step - loss: 0.3054 - accuracy: 0.8729
Epoch 72/100
25/25 [==============================] - 0s 3ms/step - loss: 0.3087 - accuracy: 0.8781
Epoch 73/100
25/25 [==============================] - 0s 4ms/step - loss: 0.3038 - accuracy: 0.8755
Epoch 74/100
25/25 [==============================] - 0s 4ms/step - loss: 0.3094 - accuracy: 0.8807
Epoch 75/100
25/25 [==============================] - 0s 4ms/step - loss: 0.2965 - accuracy: 0.8781
Epoch 76/100
25/25 [==============================] - 0s 4ms/step - loss: 0.2937 - accuracy: 0.8807
Epoch 77/100
25/25 [==============================] - 0s 4ms/step - loss: 0.3010 - accuracy: 0.8651
Epoch 78/100
25/25 [==============================] - 0s 4ms/step - loss: 0.2799 - accuracy: 0.8807
Epoch 79/100
25/25 [==============================] - 0s 4ms/step - loss: 0.2859 - accuracy: 0.8755
Epoch 80/100
25/25 [==============================] - 0s 4ms/step - loss: 0.2837 - accuracy: 0.8742
Epoch 81/100
25/25 [==============================] - 0s 3ms/step - loss: 0.2990 - accuracy: 0.8742
Epoch 82/100
25/25 [==============================] - 0s 4ms/step - loss: 0.2826 - accuracy: 0.8768
Epoch 83/100
25/25 [==============================] - 0s 4ms/step - loss: 0.2809 - accuracy: 0.8898
Epoch 84/100
25/25 [==============================] - 0s 4ms/step - loss: 0.2737 - accuracy: 0.8833
Epoch 85/100
25/25 [==============================] - 0s 4ms/step - loss: 0.3072 - accuracy: 0.8560
Epoch 86/100
25/25 [==============================] - 0s 4ms/step - loss: 0.2909 - accuracy: 0.8625
Epoch 87/100
25/25 [==============================] - 0s 4ms/step - loss: 0.2774 - accuracy: 0.8872
Epoch 88/100
25/25 [==============================] - 0s 4ms/step - loss: 0.2886 - accuracy: 0.8846
Epoch 89/100
25/25 [==============================] - 0s 4ms/step - loss: 0.2971 - accuracy: 0.8716
Epoch 90/100
25/25 [==============================] - 0s 5ms/step - loss: 0.2816 - accuracy: 0.8781
Epoch 91/100
25/25 [==============================] - 0s 5ms/step - loss: 0.2905 - accuracy: 0.8768
Epoch 92/100
25/25 [==============================] - 0s 5ms/step - loss: 0.2779 - accuracy: 0.8885
Epoch 93/100
25/25 [==============================] - 0s 4ms/step - loss: 0.2878 - accuracy: 0.8729
Epoch 94/100
25/25 [==============================] - 0s 4ms/step - loss: 0.3040 - accuracy: 0.8612
Epoch 95/100
25/25 [==============================] - 0s 4ms/step - loss: 0.2882 - accuracy: 0.8703
Epoch 96/100
25/25 [==============================] - 0s 4ms/step - loss: 0.2989 - accuracy: 0.8638
Epoch 97/100
25/25 [==============================] - 0s 3ms/step - loss: 0.3047 - accuracy: 0.8820
Epoch 98/100
25/25 [==============================] - 0s 4ms/step - loss: 0.2829 - accuracy: 0.8794
Epoch 99/100
25/25 [==============================] - 0s 4ms/step - loss: 0.3050 - accuracy: 0.8755
Epoch 100/100
25/25 [==============================] - 0s 5ms/step - loss: 0.2936 - accuracy: 0.8742

In [155]:
loss , acc = model.evaluate(x_test , y_test)
acc

7/7 [==============================] - 0s 4ms/step - loss: 0.2937 - accuracy: 0.8653

0.8652849793434143

In [156]:

RandomForestClassifier().fit(x_train , y_train).score(x_test , y_test)

0.844559585492228

El siguiente modelo se uso para la primera prediccion

In [192]:
from tensorflow.keras.activations import swish
X_encod = df_encoded.drop('Nivel de Adaptación' , axis = 1)
y_encod = df_encoded['Nivel de Adaptación']
x_train_encod , x_test_encod , y_train_encod , y_test_encod = train_test_split(X_encod , y_encod , test_size = 0.2 , random_state = 42)
model_encode = tf.keras.models.Sequential([
    tf.keras.layers.InputLayer(input_shape = x_train_encod.shape[1:]),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.Dense(100 , activation = 'relu'),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.Dense(100 , activation = "gelu"),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.Dense(3 , activation = 'softmax')
])

# Compilar el modelo
model_encode.compile(loss='sparse_categorical_crossentropy', optimizer=tf.keras.optimizers.Adam(learning_rate=0.001), metrics=['accuracy'])

# Entrenar el modelo con callbacks
callback = tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)
history = model_encode.fit(x_train_encod, y_train_encod, epochs=100, validation_split=0.2, batch_size=64, callbacks=[callback])

# Evaluar el modelo en el conjunto de test
test_loss, test_accuracy = model_encode.evaluate(x_test_encod, y_test_encod)
print(f'Test accuracy: {test_accuracy}')

Epoch 1/100
10/10 [==============================] - 2s 44ms/step - loss: 1.3641 - accuracy: 0.4334 - val_loss: 1.0145 - val_accuracy: 0.5032
Epoch 2/100
10/10 [==============================] - 0s 11ms/step - loss: 0.8942 - accuracy: 0.6234 - val_loss: 0.9803 - val_accuracy: 0.5742
Epoch 3/100
10/10 [==============================] - 0s 10ms/step - loss: 0.7273 - accuracy: 0.7094 - val_loss: 0.9878 - val_accuracy: 0.6065
Epoch 4/100
10/10 [==============================] - 0s 9ms/step - loss: 0.6451 - accuracy: 0.7662 - val_loss: 0.9872 - val_accuracy: 0.6065
Epoch 5/100
10/10 [==============================] - 0s 9ms/step - loss: 0.5623 - accuracy: 0.8003 - val_loss: 0.9731 - val_accuracy: 0.6258
Epoch 6/100
10/10 [==============================] - 0s 11ms/step - loss: 0.5347 - accuracy: 0.8052 - val_loss: 0.9505 - val_accuracy: 0.6516
Epoch 7/100
10/10 [==============================] - 0s 14ms/step - loss: 0.5060 - accuracy: 0.8279 - val_loss: 0.9347 - val_accuracy: 0.6387
Epoch 8/100
10/10 [==============================] - 0s 9ms/step - loss: 0.4804 - accuracy: 0.8149 - val_loss: 0.9267 - val_accuracy: 0.6516
Epoch 9/100
10/10 [==============================] - 0s 10ms/step - loss: 0.4463 - accuracy: 0.8279 - val_loss: 0.9062 - val_accuracy: 0.6645
Epoch 10/100
10/10 [==============================] - 0s 10ms/step - loss: 0.4256 - accuracy: 0.8377 - val_loss: 0.8872 - val_accuracy: 0.6710
Epoch 11/100
10/10 [==============================] - 0s 9ms/step - loss: 0.4052 - accuracy: 0.8523 - val_loss: 0.8798 - val_accuracy: 0.6516
Epoch 12/100
10/10 [==============================] - 0s 10ms/step - loss: 0.3892 - accuracy: 0.8653 - val_loss: 0.8522 - val_accuracy: 0.6710
Epoch 13/100
10/10 [==============================] - 0s 9ms/step - loss: 0.3879 - accuracy: 0.8588 - val_loss: 0.8228 - val_accuracy: 0.6968
Epoch 14/100
10/10 [==============================] - 0s 11ms/step - loss: 0.3642 - accuracy: 0.8734 - val_loss: 0.8040 - val_accuracy: 0.7032
Epoch 15/100
10/10 [==============================] - 0s 10ms/step - loss: 0.3497 - accuracy: 0.8734 - val_loss: 0.7904 - val_accuracy: 0.6839
Epoch 16/100
10/10 [==============================] - 0s 10ms/step - loss: 0.3551 - accuracy: 0.8571 - val_loss: 0.7643 - val_accuracy: 0.7032
Epoch 17/100
10/10 [==============================] - 0s 11ms/step - loss: 0.3471 - accuracy: 0.8604 - val_loss: 0.7394 - val_accuracy: 0.7355
Epoch 18/100
10/10 [==============================] - 0s 11ms/step - loss: 0.3346 - accuracy: 0.8718 - val_loss: 0.7213 - val_accuracy: 0.7226
Epoch 19/100
10/10 [==============================] - 0s 11ms/step - loss: 0.3230 - accuracy: 0.8864 - val_loss: 0.6936 - val_accuracy: 0.7484
Epoch 20/100
10/10 [==============================] - 0s 17ms/step - loss: 0.3116 - accuracy: 0.8847 - val_loss: 0.6763 - val_accuracy: 0.7742
Epoch 21/100
10/10 [==============================] - 0s 11ms/step - loss: 0.3224 - accuracy: 0.8766 - val_loss: 0.6546 - val_accuracy: 0.7677
Epoch 22/100
10/10 [==============================] - 0s 10ms/step - loss: 0.2968 - accuracy: 0.8880 - val_loss: 0.6366 - val_accuracy: 0.7871
Epoch 23/100
10/10 [==============================] - 0s 9ms/step - loss: 0.3068 - accuracy: 0.8864 - val_loss: 0.6152 - val_accuracy: 0.8000
Epoch 24/100
10/10 [==============================] - 0s 10ms/step - loss: 0.3073 - accuracy: 0.8815 - val_loss: 0.5956 - val_accuracy: 0.7613
Epoch 25/100
10/10 [==============================] - 0s 11ms/step - loss: 0.2917 - accuracy: 0.8880 - val_loss: 0.5832 - val_accuracy: 0.7871
Epoch 26/100
10/10 [==============================] - 0s 11ms/step - loss: 0.2858 - accuracy: 0.8799 - val_loss: 0.5759 - val_accuracy: 0.7677
Epoch 27/100
10/10 [==============================] - 0s 11ms/step - loss: 0.3013 - accuracy: 0.8815 - val_loss: 0.5555 - val_accuracy: 0.7742
Epoch 28/100
10/10 [==============================] - 0s 10ms/step - loss: 0.2709 - accuracy: 0.8896 - val_loss: 0.5325 - val_accuracy: 0.7935
Epoch 29/100
10/10 [==============================] - 0s 10ms/step - loss: 0.2807 - accuracy: 0.8750 - val_loss: 0.5171 - val_accuracy: 0.8000
Epoch 30/100
10/10 [==============================] - 0s 12ms/step - loss: 0.2917 - accuracy: 0.8864 - val_loss: 0.5085 - val_accuracy: 0.8194
Epoch 31/100
10/10 [==============================] - 0s 14ms/step - loss: 0.2736 - accuracy: 0.8945 - val_loss: 0.5008 - val_accuracy: 0.8258
Epoch 32/100
10/10 [==============================] - 0s 14ms/step - loss: 0.2859 - accuracy: 0.8685 - val_loss: 0.5034 - val_accuracy: 0.8065
Epoch 33/100
10/10 [==============================] - 0s 16ms/step - loss: 0.2909 - accuracy: 0.8831 - val_loss: 0.4797 - val_accuracy: 0.8065
Epoch 34/100
10/10 [==============================] - 0s 11ms/step - loss: 0.2731 - accuracy: 0.8831 - val_loss: 0.4816 - val_accuracy: 0.8129
Epoch 35/100
10/10 [==============================] - 0s 9ms/step - loss: 0.2548 - accuracy: 0.8896 - val_loss: 0.4866 - val_accuracy: 0.8000
Epoch 36/100
10/10 [==============================] - 0s 10ms/step - loss: 0.2652 - accuracy: 0.8831 - val_loss: 0.4825 - val_accuracy: 0.7935
Epoch 37/100
10/10 [==============================] - 0s 11ms/step - loss: 0.2611 - accuracy: 0.8961 - val_loss: 0.4650 - val_accuracy: 0.8065
Epoch 38/100
10/10 [==============================] - 0s 10ms/step - loss: 0.2561 - accuracy: 0.8961 - val_loss: 0.4634 - val_accuracy: 0.8000
Epoch 39/100
10/10 [==============================] - 0s 9ms/step - loss: 0.2585 - accuracy: 0.8912 - val_loss: 0.4517 - val_accuracy: 0.8258
Epoch 40/100
10/10 [==============================] - 0s 9ms/step - loss: 0.2532 - accuracy: 0.8864 - val_loss: 0.4546 - val_accuracy: 0.8258
Epoch 41/100
10/10 [==============================] - 0s 9ms/step - loss: 0.2619 - accuracy: 0.8847 - val_loss: 0.4700 - val_accuracy: 0.8129
Epoch 42/100
10/10 [==============================] - 0s 8ms/step - loss: 0.2606 - accuracy: 0.8929 - val_loss: 0.4573 - val_accuracy: 0.8258
Epoch 43/100
10/10 [==============================] - 0s 9ms/step - loss: 0.2601 - accuracy: 0.8896 - val_loss: 0.4701 - val_accuracy: 0.8000
Epoch 44/100
10/10 [==============================] - 0s 10ms/step - loss: 0.2758 - accuracy: 0.8734 - val_loss: 0.4795 - val_accuracy: 0.7935
Epoch 45/100
10/10 [==============================] - 0s 11ms/step - loss: 0.2558 - accuracy: 0.8912 - val_loss: 0.4711 - val_accuracy: 0.8065
Epoch 46/100
10/10 [==============================] - 0s 10ms/step - loss: 0.2548 - accuracy: 0.8929 - val_loss: 0.4729 - val_accuracy: 0.8194
Epoch 47/100
10/10 [==============================] - 0s 10ms/step - loss: 0.2487 - accuracy: 0.8945 - val_loss: 0.4631 - val_accuracy: 0.8194
Epoch 48/100
10/10 [==============================] - 0s 10ms/step - loss: 0.2549 - accuracy: 0.8799 - val_loss: 0.4938 - val_accuracy: 0.7871
Epoch 49/100
10/10 [==============================] - 0s 10ms/step - loss: 0.2789 - accuracy: 0.8766 - val_loss: 0.4730 - val_accuracy: 0.8129
7/7 [==============================] - 0s 3ms/step - loss: 0.4444 - accuracy: 0.8290
Test accuracy: 0.8290155529975891

In [181]:
loss_encod , acc_encod = model_encode.evaluate(x_test_encod , y_test_encod)
acc_encod

7/7 [==============================] - 0s 3ms/step - loss: 0.4019 - accuracy: 0.8446

0.8445596098899841

In [159]:
RandomForestClassifier().fit(x_train_encod , y_train_encod).score(x_test_encod , y_test_encod)

0.8497409326424871

In [160]:
data_test = pd.read_csv("submission-ds.csv")
data_test1 =pd.get_dummies(data_test)

In [161]:
data_test['Edad'] = data_test['Edad'].apply(convertir_mes_a_numero)
data_test['Duración de la Clase'] = data_test['Duración de la Clase'].apply(convertir_mes_a_numero)
data_test = data_test.apply(LabelEncoder().fit_transform)

In [162]:

data_test

,Tipo de Red,Estudiante de Tecnología,Nivel de Educación,Vive en Ciudad,Tipo de Instituto,Edad,Dispositivo,Tipo de Internet,Situación Financiera,Género,Duración de la Clase
0,1,0,0,0,1,3,1,0,1,1,1
1,2,0,0,0,0,2,1,1,2,0,1
2,2,0,2,1,1,3,1,0,2,1,0
3,1,1,2,0,1,3,1,0,2,1,1
4,1,0,1,0,1,5,1,0,2,0,0
...,...,...,...,...,...,...,...,...,...,...,...
236,2,0,1,1,0,0,1,1,2,0,1
237,2,0,1,1,0,0,1,0,2,0,1
238,2,0,1,1,0,1,1,0,2,1,1
239,2,0,1,1,1,2,1,1,2,1,1
240,1,0,1,1,0,1,1,0,2,1,1

In [163]:
predictions = model_encode.predict(data_test)

# Las predicciones son probabilidades para cada clase, puedes obtener la clase predicha usando argmax
predicted_classes = predictions.argmax(axis=1)

# Ahora 'predicted_classes' contiene las clases predichas para tus datos de prueba

8/8 [==============================] - 0s 2ms/step

In [164]:
print(predicted_classes)

[2 1 1 1 1 0 1 2 1 1 1 2 2 1 1 2 2 2 2 2 1 2 2 2 2 1 1 1 1 2 2 1 1 2 1 1 1
 2 2 1 2 1 1 1 2 2 2 1 1 2 2 1 2 1 2 2 1 2 2 1 2 1 1 2 1 2 1 1 1 2 1 2 1 2
 1 2 2 1 2 2 2 2 1 2 2 0 2 1 2 2 2 2 2 2 2 2 2 2 2 1 2 0 1 2 2 1 1 2 2 2 2
 1 2 1 1 2 2 2 0 1 2 1 2 1 2 1 2 1 0 1 2 1 2 2 2 2 1 1 1 2 2 2 2 1 2 1 2 2
 0 2 2 1 2 2 2 2 2 2 2 2 1 0 0 2 1 2 0 2 1 2 2 2 2 1 1 2 1 1 2 1 2 1 2 1 1
 2 1 2 2 2 2 2 1 2 2 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 1 1 2 2 1 2 2 1 2 2 2 1
 1 1 2 2 2 1 2 2 2 1 0 2 1 1 2 2 2 2 2]

In [165]:
data_test['Nivel de Adaptación'] = predicted_classes

In [166]:
resultados_prediccion = pd.DataFrame({
    'id': range(1, len(predicted_classes) + 1),
    'Nivel de Adaptación': predicted_classes
})
resultados_prediccion['Nivel de Adaptación'] = resultados_prediccion['Nivel de Adaptación'].map({0: 'Alto', 1: 'Bajo', 2: 'Moderado'})

# Mostrar el DataFrame con las etiquetas mapeadas
print(resultados_prediccion)

      id Nivel de Adaptación
0      1            Moderado
1      2                Bajo
2      3                Bajo
3      4                Bajo
4      5                Bajo
..   ...                 ...
236  237            Moderado
237  238            Moderado
238  239            Moderado
239  240            Moderado
240  241            Moderado

[241 rows x 2 columns]

In [167]:
resultados_prediccion.to_csv('resultados_prediccion2.csv', index=False)

Modelo 1

In [168]:
pedict_m1= model.predict(data_test1)
predict_model1 = pedict_m1.argmax(axis=1)
print(predict_model1)

8/8 [==============================] - 0s 3ms/step
[0 0 0 0 0 1 0 1 0 0 0 1 1 0 0 1 0 1 1 1 0 1 1 1 1 0 0 0 0 1 1 1 2 1 0 0 0
 1 1 0 1 0 0 0 1 1 1 1 0 1 1 0 1 1 1 1 0 1 1 0 1 0 0 1 0 1 0 0 0 1 0 1 0 1
 0 1 1 0 1 1 1 1 0 1 1 2 0 0 1 1 1 1 1 1 1 1 1 1 1 0 1 2 0 1 1 0 0 1 1 1 1
 0 1 1 0 1 1 1 1 0 1 0 2 0 1 0 1 0 2 0 1 0 1 1 1 1 0 0 0 1 1 1 1 0 1 1 1 1
 2 1 1 0 1 1 1 1 1 1 1 1 0 2 1 1 0 1 2 1 0 1 1 1 1 0 0 1 0 0 1 0 1 0 1 0 0
 1 0 1 1 1 1 1 0 1 1 0 0 0 0 1 0 0 1 1 1 1 1 1 1 1 0 0 1 1 0 1 1 0 1 0 1 0
 0 0 1 1 1 0 1 1 1 0 2 1 0 0 1 1 1 1 1]

In [169]:
resultados_prediccion1 = pd.DataFrame({
    'id': range(1, len(predict_model1) + 1),
    'Nivel de Adaptación': predict_model1
})
resultados_prediccion1['Nivel de Adaptación'] = resultados_prediccion1['Nivel de Adaptación'].map({0: 'Bajo', 1: 'Moderado', 2: 'Alto'})

print(resultados_prediccion1)
resultados_prediccion1.to_csv('resultados_prediccion_m1.csv', index=False)

      id Nivel de Adaptación
0      1                Bajo
1      2                Bajo
2      3                Bajo
3      4                Bajo
4      5                Bajo
..   ...                 ...
236  237            Moderado
237  238            Moderado
238  239            Moderado
239  240            Moderado
240  241            Moderado

[241 rows x 2 columns]